import roadinImg from "@/assets/images/roadin_thumbnail.jpg";
import carplanImg from "@/assets/images/carplan_thumbnail.jpg";
import objetbathImg from "@/assets/images/objetbath_thumbnail.jpg";
import koreanRestaurantImg from "@/assets/images/korean_restaurant_no_people_1786182882900.jpg";
import beautySkincareImg from "@/assets/images/beauty_skincare_1786182932542.jpg";
import hospitalImg from "@/assets/images/hospital_tjaspdlf.jpg";
import interiorConstructionImg from "@/assets/images/interior_construction.jpg";
import moveInCleaningImg from "@/assets/images/move_in_cleaning.jpg";
import corporateImg from "@/assets/images/corporate.jpg";
import oleaImg from "@/assets/images/olea_thumbnail.jpg";
import movingImg from "@/assets/images/moving_thumbnail.jpg";
import mujinImg from "@/assets/images/mujin_thumbnail.jpg";
import auraImg from "@/assets/images/aura_thumbnail.jpg";
import nexmotionImg from "@/assets/images/nexmotion_thumbnail.jpg";

export type Sample = {
  slug: string;
  industry: string;
  title: string;
  type: string[];
  tag?: string;
  purpose: string;
  features: string[];
  idealFor: string;
  /** src/assets 번들 이미지 또는 public/images 정적 경로 (없으면 자동으로 그라데이션 placeholder로 대체됨) */
  image?: string;
  /** 실제 배포된 사이트 URL이 있으면 상세페이지 미리보기 탭에서 iframe으로 그 사이트를 그대로 보여준다 */
  liveUrl?: string;
  /** 있으면 카드가 /samples/:slug 대신 이 경로로 연결된다 (예: 이미 자체 소개 페이지가 있는 플랫폼형 솔루션) */
  detailHref?: string;
  /** 있으면 상세 미리보기 상단에 관리자 시스템 데모로 가는 버튼이 함께 노출된다 */
  adminDemoHref?: string;
  /** type에 "basic-template"/"landing-template"가 있는 항목만 사용 — /templates 페이지의 업종 필터 값 */
  industryKey?: string;
  /** 추가 디자인 시안(1002, 1003…)만 직접 지정. 없으면 designCode.ts에서 1001로 계산한다 */
  designCode?: string;
};

/**
 * 최신순 정렬: 새 포트폴리오를 추가할 때는 배열 맨 앞(위)에 넣는다.
 * 메인 슬라이더/최근 노출 영역은 이 배열의 앞쪽 항목을 그대로 사용하고,
 * /samples 페이지 페이지네이션도 이 순서를 기준으로 6개씩 나눈다.
 */
export const SAMPLES: Sample[] = [
  {
    slug: "usedcar-a-template",
    industry: "중고차 매매 홈페이지",
    title: "중고차 매매 홈페이지 (랜딩형 템플릿 · 디자인 A)",
    type: ["landing-template", "small-business"],
    tag: "랜딩형 템플릿 · 중고차",
    purpose:
      "성능점검과 보증을 앞세운 화이트 · 그린의 신뢰 무드로, 이번 주 매물과 허위매물 보상제가 방문 상담으로 이어지는 중고차 매매 원페이지 템플릿입니다.",
    features: ["성능점검 공개 원칙", "이번 주 매물 카드", "허위매물 3배 보상", "구매 절차 안내"],
    idealFor: "투명한 매물 공개로 신뢰를 쌓는 중고차 매매상사",
    image: "/thumbs/usedcar-a.jpg",
    liveUrl: "/templates/usedcar-a/",
    industryKey: "usedcar",
    designCode: "USDL-1001",
  },
  {
    slug: "usedcar-b-template",
    industry: "중고차 매매 홈페이지",
    title: "중고차 매매 홈페이지 (랜딩형 템플릿 · 디자인 B)",
    type: ["landing-template", "small-business"],
    tag: "랜딩형 템플릿 · 중고차",
    purpose:
      "수입 딜러십의 다크 쇼룸 무드로, 102항목 인증 기준과 프리미엄 매물이 시승 예약으로 이어지는 인증 중고차 원페이지 템플릿입니다.",
    features: ["102항목 인증 기준", "프리미엄 매물 쇼케이스", "전담 딜러제", "시승 예약 CTA"],
    idealFor: "수입 · 준신차급 프리미엄 중고차 딜러샵",
    image: "/thumbs/usedcar-b.jpg",
    liveUrl: "/templates/usedcar-b/",
    industryKey: "usedcar",
    designCode: "USDL-1002",
  },
  {
    slug: "usedcar-c-template",
    industry: "중고차 매매 홈페이지",
    title: "중고차 매매 홈페이지 (랜딩형 템플릿 · 디자인 C)",
    type: ["landing-template", "small-business"],
    tag: "랜딩형 템플릿 · 중고차",
    purpose:
      "옐로와 네이비의 친근한 첫차 컨셉으로, 예산별 추천과 첫차 혜택 · 할부 가이드가 상담으로 이어지는 중고차 원페이지 템플릿입니다.",
    features: ["예산별 추천 차량", "첫차 3종 혜택", "할부 가이드", "중고차 용어 사전"],
    idealFor: "첫차 · 사회초년생 고객이 많은 중고차 매매상사",
    image: "/thumbs/usedcar-c.jpg",
    liveUrl: "/templates/usedcar-c/",
    industryKey: "usedcar",
    designCode: "USDL-1003",
  },
  {
    slug: "academy-b-template",
    industry: "학원 홈페이지",
    title: "학원 홈페이지 (랜딩형 템플릿 · 디자인 B)",
    type: ["landing-template", "business"],
    tag: "랜딩형 템플릿 · 학원",
    purpose:
      "성적표처럼 정직한 데이터 리포트 무드로, 향상 지표와 반별 커리큘럼 · 주간 관리 사이클이 상담 신청으로 이어지는 학원 원페이지 템플릿입니다.",
    features: ["성적 향상 지표", "반별 커리큘럼 표", "주간 관리 사이클", "상담 신청 CTA"],
    idealFor: "관리와 결과를 숫자로 증명하고 싶은 입시 · 보습학원",
    image: "/thumbs/academy-b.jpg",
    liveUrl: "/templates/academy-b/",
    industryKey: "academy",
    designCode: "ACAL-1002",
  },
  {
    slug: "academy-c-template",
    industry: "학원 홈페이지",
    title: "학원 홈페이지 (랜딩형 템플릿 · 디자인 C)",
    type: ["landing-template", "business"],
    tag: "랜딩형 템플릿 · 학원",
    purpose:
      "모눈종이와 형광펜 하이라이트의 손맛 나는 노트 무드로, 작은 교습소의 꼼꼼함이 상담 신청으로 이어지는 학원 원페이지 템플릿입니다.",
    features: ["모눈 노트 연출", "형광펜 하이라이트", "오늘의 시간표", "선생님 소개"],
    idealFor: "소수정예 · 밀착 관리가 강점인 동네 교습소 · 공부방",
    image: "/thumbs/academy-c.jpg",
    liveUrl: "/templates/academy-c/",
    industryKey: "academy",
    designCode: "ACAL-1003",
  },
  {
    slug: "auto-b-template",
    industry: "자동차정비소 홈페이지",
    title: "자동차정비소 홈페이지 (랜딩형 템플릿 · 디자인 B)",
    type: ["landing-template", "small-business"],
    tag: "랜딩형 템플릿 · 자동차정비",
    purpose:
      "건메탈에 세이프티 오렌지를 더한 개러지 인더스트리얼 무드로, 정비 항목 요금과 3단계 절차 · 수리 보증이 전화 예약으로 이어지는 정비소 원페이지 템플릿입니다.",
    features: ["정비 항목 요금 보드", "3단계 진행 절차", "수리 보증 안내", "긴급 출동 CTA"],
    idealFor: "실력으로 승부하는 수입차 · 튜닝 전문 정비소",
    image: "/thumbs/auto-b.jpg",
    liveUrl: "/templates/auto-b/",
    industryKey: "auto",
    designCode: "AUTL-1002",
  },
  {
    slug: "auto-c-template",
    industry: "자동차정비소 홈페이지",
    title: "자동차정비소 홈페이지 (랜딩형 템플릿 · 디자인 C)",
    type: ["landing-template", "small-business"],
    tag: "랜딩형 템플릿 · 자동차정비",
    purpose:
      "서비스센터처럼 밝고 깨끗한 화이트+블루 무드로, 정찰 요금표와 예약 절차 · 고객 약속이 예약 전화로 이어지는 정비소 원페이지 템플릿입니다.",
    features: ["정찰 요금표", "예약제 안내", "고객 약속 3가지", "차량 픽업 서비스"],
    idealFor: "여성 · 초보 운전자 고객이 많은 동네 카센터 · 경정비 전문점",
    image: "/thumbs/auto-c.jpg",
    liveUrl: "/templates/auto-c/",
    industryKey: "auto",
    designCode: "AUTL-1003",
  },
  {
    slug: "beauty-b-template",
    industry: "미용실 · 뷰티샵 홈페이지",
    title: "미용실 · 뷰티샵 홈페이지 (랜딩형 템플릿 · 디자인 B)",
    type: ["landing-template", "small-business"],
    tag: "랜딩형 템플릿 · 뷰티샵",
    purpose:
      "블러시 핑크와 버건디 세리프의 매거진 에디토리얼 무드로, 디자이너 지명 예약과 시술 메뉴 · 스타일 갤러리가 예약으로 이어지는 미용실 원페이지 템플릿입니다.",
    features: ["디자이너 지명 예약", "시술 메뉴 가격표", "스타일 갤러리", "첫 방문 안내"],
    idealFor: "디자이너 개인 브랜딩이 중요한 헤어살롱 · 뷰티샵",
    image: "/thumbs/beauty-b.jpg",
    liveUrl: "/templates/beauty-b/",
    industryKey: "beauty",
    designCode: "BEAL-1002",
  },
  {
    slug: "beauty-c-template",
    industry: "미용실 · 뷰티샵 홈페이지",
    title: "미용실 · 뷰티샵 홈페이지 (랜딩형 템플릿 · 디자인 C)",
    type: ["landing-template", "small-business"],
    tag: "랜딩형 템플릿 · 뷰티샵",
    purpose:
      "흑백 모노톤에 대형 타이포를 얹은 하이패션 무드로, 스타일 갤러리와 미니멀 가격표가 예약으로 이어지는 미용실 원페이지 템플릿입니다.",
    features: ["대형 타이포 히어로", "모노톤 갤러리", "미니멀 가격표", "멤버십 안내"],
    idealFor: "트렌드에 민감한 20–30대 고객층의 헤어살롱 · 바버샵",
    image: "/thumbs/beauty-c.jpg",
    liveUrl: "/templates/beauty-c/",
    industryKey: "beauty",
    designCode: "BEAL-1003",
  },
  {
    slug: "care-b-template",
    industry: "요양원·주간보호 홈페이지",
    title: "요양원·주간보호 홈페이지 (랜딩형 템플릿 · 디자인 B)",
    type: ["landing-template", "business"],
    tag: "랜딩형 템플릿 · 요양원·주간보호",
    purpose:
      "살구빛 온기와 큰 글씨로 보호자 세대까지 배려한 가족적인 무드로, 어르신의 하루 일과와 생활 공간이 상담으로 이어지는 요양원 원페이지 템플릿입니다.",
    features: ["하루 일과 타임라인", "생활 공간 소개", "면회 · 입소 안내", "큰 글씨 구성"],
    idealFor: "가족 같은 분위기를 보여주고 싶은 요양원 · 요양공동생활가정",
    image: "/thumbs/care-b.jpg",
    liveUrl: "/templates/care-b/",
    industryKey: "care",
    designCode: "CARL-1002",
  },
  {
    slug: "care-c-template",
    industry: "요양원·주간보호 홈페이지",
    title: "요양원·주간보호 홈페이지 (랜딩형 템플릿 · 디자인 C)",
    type: ["landing-template", "business"],
    tag: "랜딩형 템플릿 · 요양원·주간보호",
    purpose:
      "틸 그린과 화이트의 전문 케어 시스템 무드로, 인력 배치 수치와 프로그램 시간표 · 송영 차량 안내가 상담으로 이어지는 주간보호센터 원페이지 템플릿입니다.",
    features: ["인력 배치 수치", "프로그램 시간표", "송영 차량 안내", "등급 · 비용 안내"],
    idealFor: "체계적인 운영을 강점으로 내세우는 주간보호센터 · 재가센터",
    image: "/thumbs/care-c.jpg",
    liveUrl: "/templates/care-c/",
    industryKey: "care",
    designCode: "CARL-1003",
  },
  {
    slug: "craft-b-template",
    industry: "공방·클래스 홈페이지",
    title: "공방·클래스 홈페이지 (랜딩형 템플릿 · 디자인 B)",
    type: ["landing-template", "small-business"],
    tag: "랜딩형 템플릿 · 공방·클래스",
    purpose:
      "흙과 유약의 테라코타 톤으로, 물레 클래스와 만드는 과정 · 공방 풍경이 수강 문의로 이어지는 도자 공방 원페이지 템플릿입니다.",
    features: ["클래스 2종 소개", "만드는 과정 4단계", "공방 풍경 갤러리", "수강 문의 CTA"],
    idealFor: "원데이 · 정규 클래스를 운영하는 도예 · 핸드메이드 공방",
    image: "/thumbs/craft-b.jpg",
    liveUrl: "/templates/craft-b/",
    industryKey: "craft",
    designCode: "CRAL-1002",
  },
  {
    slug: "craft-c-template",
    industry: "공방·클래스 홈페이지",
    title: "공방·클래스 홈페이지 (랜딩형 템플릿 · 디자인 C)",
    type: ["landing-template", "small-business"],
    tag: "랜딩형 템플릿 · 공방·클래스",
    purpose:
      "갤러리처럼 절제된 웜 그레이 무드로, 작품 그리드와 티켓형 클래스 안내가 수강 문의로 이어지는 아틀리에 원페이지 템플릿입니다.",
    features: ["작품 그리드 갤러리", "티켓형 클래스 안내", "작가 노트", "위탁 · 주문 제작 안내"],
    idealFor: "작품 판매와 클래스를 함께 하는 작가 공방 · 아틀리에",
    image: "/thumbs/craft-c.jpg",
    liveUrl: "/templates/craft-c/",
    industryKey: "craft",
    designCode: "CRAL-1003",
  },
  {
    slug: "dental-b-template",
    industry: "치과 홈페이지",
    title: "치과 홈페이지 (랜딩형 템플릿 · 디자인 B)",
    type: ["landing-template", "small-business"],
    tag: "랜딩형 템플릿 · 치과",
    purpose:
      "민트와 라운드의 친근한 무드로, 치과 공포를 낮추는 설명과 진료 3단계가 예약으로 이어지는 치과 원페이지 템플릿입니다.",
    features: ["안심 진료 3단계", "겁내지 않아도 되는 이유", "진료 과목 안내", "예약 전화 CTA"],
    idealFor: "아이부터 어른까지, 치과가 무서운 환자를 위한 동네 치과",
    image: "/thumbs/dental-b.jpg",
    liveUrl: "/templates/dental-b/",
    industryKey: "dental",
    designCode: "DENL-1002",
  },
  {
    slug: "dental-c-template",
    industry: "치과 홈페이지",
    title: "치과 홈페이지 (랜딩형 템플릿 · 디자인 C)",
    type: ["landing-template", "small-business"],
    tag: "랜딩형 템플릿 · 치과",
    purpose:
      "딥블루에 골드 디테일을 더한 프리미엄 덴탈 랩 무드로, 임플란트 보증 제도와 디지털 장비 · 진료 철학이 상담으로 이어지는 치과 원페이지 템플릿입니다.",
    features: ["보증 제도 안내", "디지털 장비 소개", "진료 철학", "상담 예약 CTA"],
    idealFor: "임플란트 · 보철 중심의 프리미엄 치과",
    image: "/thumbs/dental-c.jpg",
    liveUrl: "/templates/dental-c/",
    industryKey: "dental",
    designCode: "DENL-1003",
  },
  {
    slug: "fitness-b-template",
    industry: "필라테스 · 헬스장 홈페이지",
    title: "필라테스 · 헬스장 홈페이지 (랜딩형 템플릿 · 디자인 B)",
    type: ["landing-template", "small-business"],
    tag: "랜딩형 템플릿 · 필라테스·헬스",
    purpose:
      "블랙에 크림슨 레드를 꽂은 고강도 에너지 무드로, 회원 변화 수치와 프로그램 · 코치 소개가 체험 신청으로 이어지는 PT 스튜디오 원페이지 템플릿입니다.",
    features: ["변화 수치 카운터", "프로그램 3종", "코치 소개", "체험 신청 CTA"],
    idealFor: "몸의 변화를 결과로 증명하는 PT · 크로스핏 스튜디오",
    image: "/thumbs/fitness-b.jpg",
    liveUrl: "/templates/fitness-b/",
    industryKey: "fitness",
    designCode: "FITL-1002",
  },
  {
    slug: "fitness-c-template",
    industry: "필라테스 · 헬스장 홈페이지",
    title: "필라테스 · 헬스장 홈페이지 (랜딩형 템플릿 · 디자인 C)",
    type: ["landing-template", "small-business"],
    tag: "랜딩형 템플릿 · 필라테스·헬스",
    purpose:
      "라벤더 크림 톤의 얇은 세리프 무드로, 기구 수업 시간표와 강사 소개가 체험 예약으로 이어지는 필라테스 스튜디오 원페이지 템플릿입니다.",
    features: ["주간 수업 시간표", "클래스 구성 안내", "강사 소개", "체험 예약 CTA"],
    idealFor: "소규모 정원제로 운영하는 기구 필라테스 · 요가 스튜디오",
    image: "/thumbs/fitness-c.jpg",
    liveUrl: "/templates/fitness-c/",
    industryKey: "fitness",
    designCode: "FITL-1003",
  },
  {
    slug: "flower-b-template",
    industry: "꽃집·플라워샵 홈페이지",
    title: "꽃집·플라워샵 홈페이지 (랜딩형 템플릿 · 디자인 B)",
    type: ["landing-template", "small-business"],
    tag: "랜딩형 템플릿 · 꽃집",
    purpose:
      "화이트에 그린 세리프를 얹은 보태니컬 무드로, 시즌 부케와 정기 꽃 구독이 주문 문의로 이어지는 플라워샵 원페이지 템플릿입니다.",
    features: ["시즌 부케 갤러리", "정기 꽃 구독 플랜", "주문 · 배송 안내", "공간 연출 의뢰"],
    idealFor: "구독 · 정기 배송을 키우고 싶은 플라워샵 · 플로리스트",
    image: "/thumbs/flower-b.jpg",
    liveUrl: "/templates/flower-b/",
    industryKey: "flower",
    designCode: "FLOL-1002",
  },
  {
    slug: "flower-c-template",
    industry: "꽃집·플라워샵 홈페이지",
    title: "꽃집·플라워샵 홈페이지 (랜딩형 템플릿 · 디자인 C)",
    type: ["landing-template", "small-business"],
    tag: "랜딩형 템플릿 · 꽃집",
    purpose:
      "라일락 · 피치 · 버터 옐로의 마카롱 팔레트로, 오늘의 단 스페셜과 가격 태그 보드가 주문 전화로 이어지는 동네 꽃집 원페이지 템플릿입니다.",
    features: ["오늘의 단 스페셜", "가격 태그 보드", "단골 쿠폰 제도", "꽃말 카드 서비스"],
    idealFor: "지나가다 들르는 손님이 많은 동네 꽃집 · 꽃 트럭",
    image: "/thumbs/flower-c.jpg",
    liveUrl: "/templates/flower-c/",
    industryKey: "flower",
    designCode: "FLOL-1003",
  },
  {
    slug: "golf-b-template",
    industry: "스크린골프 홈페이지",
    title: "스크린골프 홈페이지 (랜딩형 템플릿 · 디자인 B)",
    type: ["landing-template", "small-business"],
    tag: "랜딩형 템플릿 · 스크린골프",
    purpose:
      "다크에 그린 네온 스코어보드를 띄운 무드로, 타석 요금표와 룸 안내가 예약 전화로 이어지는 스크린골프 원페이지 템플릿입니다.",
    features: ["스코어보드 요금표", "룸 시설 안내", "심야 할인 안내", "단체전 · 회식 안내"],
    idealFor: "심야 손님과 모임 수요가 많은 스크린골프 · 실내골프연습장",
    image: "/thumbs/golf-b.jpg",
    liveUrl: "/templates/golf-b/",
    industryKey: "golf",
    designCode: "GOLL-1002",
  },
  {
    slug: "golf-c-template",
    industry: "스크린골프 홈페이지",
    title: "스크린골프 홈페이지 (랜딩형 템플릿 · 디자인 C)",
    type: ["landing-template", "small-business"],
    tag: "랜딩형 템플릿 · 스크린골프",
    purpose:
      "아이보리와 포레스트 그린의 클래식 클럽하우스 무드로, 멤버십 티어와 라운지 서비스가 가입 상담으로 이어지는 골프라운지 원페이지 템플릿입니다.",
    features: ["멤버십 티어 안내", "라운지 서비스", "프로 레슨 안내", "가입 상담 CTA"],
    idealFor: "멤버십 중심으로 운영하는 프리미엄 골프라운지 · 아카데미",
    image: "/thumbs/golf-c.jpg",
    liveUrl: "/templates/golf-c/",
    industryKey: "golf",
    designCode: "GOLL-1003",
  },
  {
    slug: "interior-b-template",
    industry: "인테리어 · 리모델링 홈페이지",
    title: "인테리어 · 리모델링 홈페이지 (랜딩형 템플릿 · 디자인 B)",
    type: ["landing-template", "business"],
    tag: "랜딩형 템플릿 · 인테리어·리모델링",
    purpose:
      "도면과 치수선 모티프의 블루프린트 무드로, 시공 전후 비교와 공정 · 견적 기준 공개가 상담으로 이어지는 인테리어 원페이지 템플릿입니다.",
    features: ["시공 전후 비교", "공정 타임라인", "견적 기준 공개", "실측 상담 CTA"],
    idealFor: "견적 투명성으로 신뢰를 쌓는 인테리어 · 리모델링 업체",
    image: "/thumbs/interior-b.jpg",
    liveUrl: "/templates/interior-b/",
    industryKey: "interior",
    designCode: "INTL-1002",
  },
  {
    slug: "interior-c-template",
    industry: "인테리어 · 리모델링 홈페이지",
    title: "인테리어 · 리모델링 홈페이지 (랜딩형 템플릿 · 디자인 C)",
    type: ["landing-template", "business"],
    tag: "랜딩형 템플릿 · 인테리어·리모델링",
    purpose:
      "원목과 베이지의 따뜻한 스튜디오 무드로, 포트폴리오와 스타일 철학이 상담 신청으로 이어지는 주거 인테리어 원페이지 템플릿입니다.",
    features: ["포트폴리오 그리드", "스타일 철학", "진행 안내", "상담 신청 CTA"],
    idealFor: "감성 주거 인테리어 · 신혼집 스타일링 스튜디오",
    image: "/thumbs/interior-c.jpg",
    liveUrl: "/templates/interior-c/",
    industryKey: "interior",
    designCode: "INTL-1003",
  },
  {
    slug: "kids-b-template",
    industry: "어린이집·유치원 홈페이지",
    title: "어린이집·유치원 홈페이지 (랜딩형 템플릿 · 디자인 B)",
    type: ["landing-template", "small-business"],
    tag: "랜딩형 템플릿 · 어린이집·유치원",
    purpose:
      "크레용 원색과 둥근 도형의 명랑한 무드로, 아이의 하루 일과와 안전 약속이 입소 상담으로 이어지는 어린이집 원페이지 템플릿입니다.",
    features: ["하루 일과 안내", "교실 · 급식 소개", "안전 약속 4가지", "입소 상담 CTA"],
    idealFor: "밝고 안전한 분위기를 보여주고 싶은 어린이집 · 유치원",
    image: "/thumbs/kids-b.jpg",
    liveUrl: "/templates/kids-b/",
    industryKey: "kids",
    designCode: "KIDL-1002",
  },
  {
    slug: "kids-c-template",
    industry: "어린이집·유치원 홈페이지",
    title: "어린이집·유치원 홈페이지 (랜딩형 템플릿 · 디자인 C)",
    type: ["landing-template", "small-business"],
    tag: "랜딩형 템플릿 · 어린이집·유치원",
    purpose:
      "세이지 그린과 테라코타의 차분한 자연 무드로, 숲 놀이 교육 철학과 사계절 활동이 입학 상담으로 이어지는 유치원 원페이지 템플릿입니다.",
    features: ["숲 교육 철학", "사계절 활동 안내", "하루 리듬", "입학 상담 CTA"],
    idealFor: "자연 · 생태 교육을 내세우는 숲 유치원 · 놀이학교",
    image: "/thumbs/kids-c.jpg",
    liveUrl: "/templates/kids-c/",
    industryKey: "kids",
    designCode: "KIDL-1003",
  },
  {
    slug: "law-b-template",
    industry: "법률사무소 홈페이지",
    title: "법률사무소 홈페이지 (랜딩형 템플릿 · 디자인 B)",
    type: ["landing-template", "business"],
    tag: "랜딩형 템플릿 · 법률사무소",
    purpose:
      "판례집의 목차처럼 절제된 아이보리 · 먹색 세리프 무드로, 수행 분야와 수임 원칙이 상담 예약으로 이어지는 법률사무소 원페이지 템플릿입니다.",
    features: ["수행 분야 목차", "변호사 소개", "수임료 원칙", "비밀 상담 안내"],
    idealFor: "신뢰와 격식을 갖춘 개인 · 소형 법률사무소",
    image: "/thumbs/law-b.jpg",
    liveUrl: "/templates/law-b/",
    industryKey: "law",
    designCode: "LAWL-1002",
  },
  {
    slug: "law-c-template",
    industry: "법률사무소 홈페이지",
    title: "법률사무소 홈페이지 (랜딩형 템플릿 · 디자인 C)",
    type: ["landing-template", "business"],
    tag: "랜딩형 템플릿 · 법률사무소",
    purpose:
      "차콜과 스틸의 단단한 소송 전문 무드로, 수행 실적 수치와 대응 절차가 긴급 상담으로 이어지는 법무법인 원페이지 템플릿입니다.",
    features: ["수행 실적 수치", "단계별 대응 절차", "변호사 팀 소개", "긴급 상담 CTA"],
    idealFor: "형사 · 기업 소송 중심의 법무법인 · 합동법률사무소",
    image: "/thumbs/law-c.jpg",
    liveUrl: "/templates/law-c/",
    industryKey: "law",
    designCode: "LAWL-1003",
  },
  {
    slug: "moving-b-template",
    industry: "이사 · 청소업체 홈페이지",
    title: "이사 · 청소업체 홈페이지 (랜딩형 템플릿 · 디자인 B)",
    type: ["landing-template", "business"],
    tag: "랜딩형 템플릿 · 이사·청소업체",
    purpose:
      "박스 테이프의 옐로 · 블랙 무드로, 견적 3단계와 작업 전후 · 파손 보상제가 전화 견적으로 이어지는 이사업체 원페이지 템플릿입니다.",
    features: ["견적 3단계", "작업 전후 비교", "파손 보상제", "이사 짐 체크리스트"],
    idealFor: "포장이사 · 원룸이사 전문 업체",
    image: "/thumbs/moving-b.jpg",
    liveUrl: "/templates/moving-b/",
    industryKey: "moving",
    designCode: "MOVL-1002",
  },
  {
    slug: "moving-c-template",
    industry: "이사 · 청소업체 홈페이지",
    title: "이사 · 청소업체 홈페이지 (랜딩형 템플릿 · 디자인 C)",
    type: ["landing-template", "business"],
    tag: "랜딩형 템플릿 · 이사·청소업체",
    purpose:
      "새집 냄새 나는 스카이 블루 · 화이트 무드로, 청소 범위 체크리스트와 작업 전후가 예약으로 이어지는 입주청소 원페이지 템플릿입니다.",
    features: ["청소 범위 체크리스트", "작업 전후 비교", "평형별 요금", "체크리스트 검수"],
    idealFor: "입주 · 이사 청소, 준공 청소 전문 업체",
    image: "/thumbs/moving-c.jpg",
    liveUrl: "/templates/moving-c/",
    industryKey: "moving",
    designCode: "MOVL-1003",
  },
  {
    slug: "photo-b-template",
    industry: "사진관 · 스튜디오 홈페이지",
    title: "사진관 · 스튜디오 홈페이지 (랜딩형 템플릿 · 디자인 B)",
    type: ["landing-template", "small-business"],
    tag: "랜딩형 템플릿 · 사진관",
    purpose:
      "암실의 어둠과 인화지의 따뜻함을 담은 다크룸 무드로, 콘택트 시트 갤러리와 촬영 상품이 예약으로 이어지는 사진관 원페이지 템플릿입니다.",
    features: ["콘택트 시트 갤러리", "촬영 상품 목록", "작가 소개", "촬영 예약 CTA"],
    idealFor: "흑백 · 필름 감성의 인물 전문 사진관",
    image: "/thumbs/photo-b.jpg",
    liveUrl: "/templates/photo-b/",
    industryKey: "photo",
    designCode: "PHOL-1002",
  },
  {
    slug: "photo-c-template",
    industry: "사진관 · 스튜디오 홈페이지",
    title: "사진관 · 스튜디오 홈페이지 (랜딩형 템플릿 · 디자인 C)",
    type: ["landing-template", "small-business"],
    tag: "랜딩형 템플릿 · 사진관",
    purpose:
      "여백을 살린 순백 미니멀 무드로, 가족 · 아기 촬영 패키지와 예약 절차가 예약으로 이어지는 사진관 원페이지 템플릿입니다.",
    features: ["촬영 패키지 3종", "예약 절차 안내", "미니멀 갤러리", "가족 촬영 안내"],
    idealFor: "가족 · 아기 · 리마인드 촬영 중심의 밝은 스튜디오",
    image: "/thumbs/photo-c.jpg",
    liveUrl: "/templates/photo-c/",
    industryKey: "photo",
    designCode: "PHOL-1003",
  },
  {
    slug: "study-b-template",
    industry: "스터디카페 홈페이지",
    title: "스터디카페 홈페이지 (랜딩형 템플릿 · 디자인 B)",
    type: ["landing-template", "small-business"],
    tag: "랜딩형 템플릿 · 스터디카페",
    purpose:
      "데스크 램프의 앰버 빛을 살린 심야 몰입 무드로, 좌석 존과 이용권 요금이 방문으로 이어지는 스터디카페 원페이지 템플릿입니다.",
    features: ["좌석 존 3종 안내", "이용권 요금표", "몰입 규칙", "24시간 무인 안내"],
    idealFor: "심야 · 새벽 이용이 많은 24시 스터디카페",
    image: "/thumbs/study-b.jpg",
    liveUrl: "/templates/study-b/",
    industryKey: "study",
    designCode: "STUL-1002",
  },
  {
    slug: "study-c-template",
    industry: "스터디카페 홈페이지",
    title: "스터디카페 홈페이지 (랜딩형 템플릿 · 디자인 C)",
    type: ["landing-template", "small-business"],
    tag: "랜딩형 템플릿 · 스터디카페",
    purpose:
      "도서관의 정숙함을 닮은 미색 화이트 무드로, 이용권 표와 학부모 안심 서비스가 방문으로 이어지는 스터디카페 원페이지 템플릿입니다.",
    features: ["이용권 요금표", "입퇴실 알림 서비스", "시설 안내", "학습 환경 원칙"],
    idealFor: "중고등학생 · 학부모 신뢰가 중요한 동네 스터디카페",
    image: "/thumbs/study-c.jpg",
    liveUrl: "/templates/study-c/",
    industryKey: "study",
    designCode: "STUL-1003",
  },
  {
    slug: "tax-b-template",
    industry: "세무사·회계사무소 홈페이지",
    title: "세무사·회계사무소 홈페이지 (랜딩형 템플릿 · 디자인 B)",
    type: ["landing-template", "business"],
    tag: "랜딩형 템플릿 · 세무·회계",
    purpose:
      "장부 원장(Ledger)의 그린 라인 무드로, 투명한 수임료 표와 기장 서비스 범위가 상담으로 이어지는 세무회계 원페이지 템플릿입니다.",
    features: ["수임료 정찰 표", "기장 서비스 범위", "월별 세무 일정", "세무사 소개"],
    idealFor: "수임료를 투명하게 공개하는 개인 · 소규모 세무회계사무소",
    image: "/thumbs/tax-b.jpg",
    liveUrl: "/templates/tax-b/",
    industryKey: "tax",
    designCode: "TAXL-1002",
  },
  {
    slug: "tax-c-template",
    industry: "세무사·회계사무소 홈페이지",
    title: "세무사·회계사무소 홈페이지 (랜딩형 템플릿 · 디자인 C)",
    type: ["landing-template", "business"],
    tag: "랜딩형 템플릿 · 세무·회계",
    purpose:
      "네이비와 민트의 파트너십 무드로, 업종별 전문 기장과 플랜 카드가 상담으로 이어지는 세무회계 원페이지 템플릿입니다.",
    features: ["업종별 전문 기장", "파트너 플랜 카드", "상담 절차", "절세 리포트 안내"],
    idealFor: "스타트업 · 온라인셀러 등 젊은 사업자 고객층의 세무사무소",
    image: "/thumbs/tax-c.jpg",
    liveUrl: "/templates/tax-c/",
    industryKey: "tax",
    designCode: "TAXL-1003",
  },
  {
    slug: "vet-b-template",
    industry: "동물병원 홈페이지",
    title: "동물병원 홈페이지 (랜딩형 템플릿 · 디자인 B)",
    type: ["landing-template", "small-business"],
    tag: "랜딩형 템플릿 · 동물병원",
    purpose:
      "크림 · 피치의 다정한 무드로, 겁 많은 아이를 위한 진료 방식과 예방접종 캘린더가 예약으로 이어지는 동물병원 원페이지 템플릿입니다.",
    features: ["무서움 줄이는 진료", "예방접종 캘린더", "수의사 소개", "진료 예약 CTA"],
    idealFor: "보호자 소통을 중시하는 동네 동물병원",
    image: "/thumbs/vet-b.jpg",
    liveUrl: "/templates/vet-b/",
    industryKey: "vet",
    designCode: "VETL-1002",
  },
  {
    slug: "vet-c-template",
    industry: "동물병원 홈페이지",
    title: "동물병원 홈페이지 (랜딩형 템플릿 · 디자인 C)",
    type: ["landing-template", "small-business"],
    tag: "랜딩형 템플릿 · 동물병원",
    purpose:
      "틸 그린의 신뢰감 있는 메디컬 무드로, 응급 대응 절차와 진료 과목 · 장비가 응급 전화로 이어지는 24시 동물병원 원페이지 템플릿입니다.",
    features: ["24시 응급 절차", "진료 과목 안내", "검사 장비 안내", "응급 전화 CTA"],
    idealFor: "야간 · 응급 진료 중심의 24시 동물병원 · 의료센터",
    image: "/thumbs/vet-c.jpg",
    liveUrl: "/templates/vet-c/",
    industryKey: "vet",
    designCode: "VETL-1003",
  },
  {
    slug: "rentcar-b-template",
    industry: "렌트카 홈페이지",
    title: "렌트카 홈페이지 (랜딩형 템플릿 · 디자인 B)",
    type: ["landing-template", "business"],
    tag: "랜딩형 템플릿 · 렌트카",
    purpose:
      "다크 쇼룸 무드에 라임 포인트를 더한 프리미엄 구성으로, 가로 스크롤 차량 쇼룸에서 요금 · 보험 안내를 지나 예약 전화까지 이어지는 렌트카 원페이지 템플릿입니다.",
    features: ["가로 스크롤 차량 쇼룸", "기간별 요금 플랜", "보험 포함가 안내", "예약 전화 CTA"],
    idealFor: "수입차 · 신차 위주 라인업으로 프리미엄 인상을 주고 싶은 렌트카 업체",
    image: "/thumbs/rentcar-b.jpg",
    liveUrl: "/templates/rentcar-b/",
    industryKey: "rentcar",
    designCode: "RENL-1002",
  },
  {
    slug: "rentcar-c-template",
    industry: "렌트카 홈페이지",
    title: "렌트카 홈페이지 (랜딩형 템플릿 · 디자인 C)",
    type: ["landing-template", "business"],
    tag: "랜딩형 템플릿 · 렌트카",
    purpose:
      "밝고 친근한 로드트립 무드로, 가족 여행객이 차량 고르기부터 추천 코스 · 예약 전화까지 즐겁게 따라오는 렌트카 원페이지 템플릿입니다.",
    features: ["여행 무드 일러스트 연출", "가족별 차량 추천", "티켓형 요금제", "추천 여행 코스"],
    idealFor: "가족 · 관광객 손님이 많은 여행지 렌트카 업체",
    image: "/thumbs/rentcar-c.jpg",
    liveUrl: "/templates/rentcar-c/",
    industryKey: "rentcar",
    designCode: "RENL-1003",
  },
  {
    slug: "real-estate-b-template",
    industry: "부동산 중개업소 홈페이지",
    title: "부동산 홈페이지 (랜딩형 템플릿 · 디자인 B)",
    type: ["landing-template", "small-business"],
    tag: "랜딩형 템플릿 · 부동산",
    purpose:
      "매거진처럼 매물을 감상하는 화이트 에디토리얼 구성으로, 중개 철학과 매물 큐레이션으로 신뢰를 만드는 부동산 원페이지 템플릿입니다.",
    features: ["갤러리형 매물 큐레이션", "중개 철학 인용부", "중개 서비스 안내", "상담 시간 안내"],
    idealFor: "단독주택 · 프리미엄 매물을 감도 있게 보여주고 싶은 공인중개사사무소",
    image: "/thumbs/realestate-b.jpg",
    liveUrl: "/templates/realestate-b/",
    industryKey: "real-estate",
    designCode: "REAL-1002",
  },
  {
    slug: "real-estate-c-template",
    industry: "부동산 중개업소 홈페이지",
    title: "부동산 홈페이지 (랜딩형 템플릿 · 디자인 C)",
    type: ["landing-template", "small-business"],
    tag: "랜딩형 템플릿 · 부동산",
    purpose:
      "네이비와 골드의 자산 리포트 무드로, 시세 데이터 · 수익률 테이블 · 투자 브리핑 절차를 갖춘 수익형 전문 부동산 원페이지 템플릿입니다.",
    features: ["시장 데이터 위젯", "수익률 매물 테이블", "투자 브리핑 절차", "신뢰 기준 안내"],
    idealFor: "상가 · 수익형 부동산을 데이터로 브리핑하는 중개법인 · 컨설팅",
    image: "/thumbs/realestate-c.jpg",
    liveUrl: "/templates/realestate-c/",
    industryKey: "real-estate",
    designCode: "REAL-1003",
  },
  {
    slug: "restaurant-b-template",
    industry: "음식점 · 카페 홈페이지",
    title: "음식점 · 카페 홈페이지 (랜딩형 템플릿 · 디자인 B)",
    type: ["landing-template", "business"],
    tag: "랜딩형 템플릿 · 음식점 · 카페",
    purpose:
      "먹빛 배경에 금색 획을 더한 모던 한정식 무드로, 세로쓰기 타이포와 계절 코스 메뉴가 예약으로 이어지는 다이닝 원페이지 템플릿입니다.",
    features: ["세로쓰기 타이포 연출", "계절 코스 메뉴 탭", "룸 공간 소개", "예약제 안내"],
    idealFor: "코스 · 예약제로 운영하는 한정식 · 오마카세 · 파인다이닝",
    image: "/thumbs/restaurant-b.jpg",
    liveUrl: "/templates/restaurant-b/",
    industryKey: "restaurant",
    designCode: "RESL-1002",
  },
  {
    slug: "restaurant-c-template",
    industry: "음식점 · 카페 홈페이지",
    title: "음식점 · 카페 홈페이지 (랜딩형 템플릿 · 디자인 C)",
    type: ["landing-template", "business"],
    tag: "랜딩형 템플릿 · 음식점 · 카페",
    purpose:
      "스티커 배지와 손그림 무드의 경쾌한 팝 비스트로 구성으로, 요일 스페셜과 메뉴판을 지나 전화 주문까지 이어지는 동네 맛집 원페이지 템플릿입니다.",
    features: ["스티커 배지 연출", "요일별 스페셜 보드", "사진 메뉴판", "영업중 표시 · 전화 주문"],
    idealFor: "단골 장사가 중심인 동네 식당 · 분식 · 캐주얼 비스트로",
    image: "/thumbs/restaurant-c.jpg",
    liveUrl: "/templates/restaurant-c/",
    industryKey: "restaurant",
    designCode: "RESL-1003",
  },
  {
    slug: "corporate-b-template",
    industry: "기업 · 브랜드 홈페이지",
    title: "기업 · 브랜드 홈페이지 (랜딩형 템플릿 · 디자인 B)",
    type: ["landing-template", "business"],
    tag: "랜딩형 템플릿 · 기업 · 브랜드",
    purpose:
      "딥테크 SaaS 무드의 다크 그라디언트 구성으로, 글래스 대시보드 목업과 벤토 그리드 · 지표 카운터가 도입 문의로 이어지는 기업 원페이지 템플릿입니다.",
    features: ["대시보드 목업 히어로", "벤토 그리드 사업영역", "지표 카운트업", "고객사 로고 스트립"],
    idealFor: "IT 솔루션 · SaaS · 스마트팩토리 등 기술력을 보여줘야 하는 기업",
    image: "/thumbs/corporate-b.jpg",
    liveUrl: "/templates/corporate-b/",
    industryKey: "corporate",
    designCode: "CORL-1002",
  },
  {
    slug: "corporate-c-template",
    industry: "기업 · 브랜드 홈페이지",
    title: "기업 · 브랜드 홈페이지 (랜딩형 템플릿 · 디자인 C)",
    type: ["landing-template", "business"],
    tag: "랜딩형 템플릿 · 기업 · 브랜드",
    purpose:
      "포레스트 그린과 샌드 톤의 유기적인 곡선 구성으로, 아치형 이미지 프레임과 환경 성과 지표가 협력 문의로 이어지는 친환경 기업 원페이지 템플릿입니다.",
    features: ["아치 프레임 히어로", "곡선 섹션 연출", "환경 성과 지표", "진행 절차 플로우"],
    idealFor: "에너지 · 환경 · 농식품 등 자연 · ESG 이미지가 중요한 기업",
    image: "/thumbs/corporate-c.jpg",
    liveUrl: "/templates/corporate-c/",
    industryKey: "corporate",
    designCode: "CORL-1003",
  },
  {
    slug: "clinic-b-template",
    industry: "병원 · 의원 홈페이지",
    title: "병원 · 의원 홈페이지 (랜딩형 템플릿 · 디자인 B)",
    type: ["landing-template", "business"],
    tag: "랜딩형 템플릿 · 병원 · 의원",
    purpose:
      "세이지 그린의 힐링 무드로, 숨 쉬듯 번지는 원 모티프와 진료 원칙 · 의료진 소개가 편안하게 예약으로 이어지는 의원 원페이지 템플릿입니다.",
    features: ["브리딩 애니메이션", "진료과목 카드", "진료 원칙 3계명", "진료시간 · 오시는 길"],
    idealFor: "내과 · 가정의학과 등 편안한 첫인상이 중요한 동네 주치의 의원",
    image: "/thumbs/clinic-b.jpg",
    liveUrl: "/templates/clinic-b/",
    industryKey: "hospital",
    designCode: "HOSL-1002",
  },
  {
    slug: "clinic-c-template",
    industry: "병원 · 의원 홈페이지",
    title: "병원 · 의원 홈페이지 (랜딩형 템플릿 · 디자인 C)",
    type: ["landing-template", "business"],
    tag: "랜딩형 템플릿 · 병원 · 의원",
    purpose:
      "화이트와 코발트 블루의 스마트 메디컬 무드로, 진료 절차 스텝퍼와 장비 안내 · 비급여 수가표까지 투명하게 공개하는 의원 원페이지 템플릿입니다.",
    features: ["진료 절차 스텝퍼", "보유 장비 안내", "비급여 수가표", "당일 검사 안내"],
    idealFor: "정형외과 · 재활의학과 등 장비와 절차를 명확히 보여줘야 하는 의원",
    image: "/thumbs/clinic-c.jpg",
    liveUrl: "/templates/clinic-c/",
    industryKey: "hospital",
    designCode: "HOSL-1003",
  },
  {
    slug: "stay-b-template",
    industry: "펜션 · 스테이 홈페이지",
    title: "펜션 · 스테이 홈페이지 (랜딩형 템플릿 · 디자인 B)",
    type: ["landing-template", "small-business"],
    tag: "랜딩형 템플릿 · 펜션 · 스테이",
    purpose:
      "여백을 넓게 쓴 노르딕 미니멀 구성으로, 절제된 그리드 갤러리와 객실별 스펙 시트가 조용히 예약으로 이어지는 스테이 원페이지 템플릿입니다.",
    features: ["미니멀 그리드 갤러리", "객실 스펙 시트", "이용 안내 시트", "예약 전화 · 문자"],
    idealFor: "노키즈 · 소수 객실로 운영하는 감성 독채 스테이",
    image: "/thumbs/stay-b.jpg",
    liveUrl: "/templates/stay-b/",
    industryKey: "stay",
    designCode: "STAL-1002",
  },
  {
    slug: "stay-c-template",
    industry: "펜션 · 스테이 홈페이지",
    title: "펜션 · 스테이 홈페이지 (랜딩형 템플릿 · 디자인 C)",
    type: ["landing-template", "small-business"],
    tag: "랜딩형 템플릿 · 펜션 · 스테이",
    purpose:
      "폴라로이드와 손글씨 메모의 스크랩북 저널 무드로, 주인의 일기와 방명록 한 줄이 정겹게 예약으로 이어지는 가족 펜션 원페이지 템플릿입니다.",
    features: ["폴라로이드 갤러리", "손글씨 메모 연출", "방명록 후기 카드", "이용 안내 시트"],
    idealFor: "가족 · 아이 손님이 많은 시골 펜션 · 민박",
    image: "/thumbs/stay-c.jpg",
    liveUrl: "/templates/stay-c/",
    industryKey: "stay",
    designCode: "STAL-1003",
  },
  {
    slug: "law-basic-template",
    industry: "법률사무소 홈페이지",
    title: "법률사무소 홈페이지 (기본형 템플릿)",
    type: ["basic-template", "business"],
    tag: "기본형 템플릿 · 법률사무소",
    purpose:
      "수행 분야와 진행 절차, 서면으로 확정하는 수임료 원칙까지 — 판례집처럼 절제된 톤으로 신뢰를 만드는 법률사무소 템플릿입니다.",
    features: ["수행 분야 목차", "진행 절차 안내", "수임료 원칙", "비밀 상담 문의"],
    idealFor: "정직한 전망과 투명한 수임료로 수임을 늘리고 싶은 법률사무소 · 변호사",
    image: "/thumbs/law.jpg",
    liveUrl: "/templates/law-basic/",
    industryKey: "law",
  },
  {
    slug: "law-landing-template",
    industry: "법률사무소 홈페이지",
    title: "법률사무소 홈페이지 (랜딩형 템플릿)",
    type: ["landing-template", "business"],
    tag: "랜딩형 템플릿 · 법률사무소",
    purpose:
      "수행 분야와 진행 절차, 서면으로 확정하는 수임료 원칙까지 — 판례집처럼 절제된 톤으로 신뢰를 만드는 법률사무소 원페이지 템플릿입니다.",
    features: ["스크롤 애니메이션", "수행 분야 목차", "수임료 원칙", "비밀 상담 CTA"],
    idealFor: "정직한 전망과 투명한 수임료로 수임을 늘리고 싶은 법률사무소 · 변호사",
    image: "/thumbs/law.jpg",
    liveUrl: "/templates/law-landing/",
    industryKey: "law",
  },
  {
    slug: "study-basic-template",
    industry: "스터디카페 홈페이지",
    title: "스터디카페 홈페이지 (기본형 템플릿)",
    type: ["basic-template", "small-business"],
    tag: "기본형 템플릿 · 스터디카페",
    purpose:
      "실시간 잔여석 보드, 시간권·기간권·고정석 요금표, 좌석·시설 안내까지 담은 24시간 스터디카페 템플릿입니다.",
    features: ["실시간 잔여석 보드", "시간권 · 기간권 요금표", "좌석 안내", "무인 이용 안내"],
    idealFor: "요금과 좌석을 투명하게 열어 신규 방문을 늘리고 싶은 스터디카페 · 독서실",
    image: "/thumbs/study.jpg",
    liveUrl: "/templates/study-basic/",
    industryKey: "study",
  },
  {
    slug: "study-landing-template",
    industry: "스터디카페 홈페이지",
    title: "스터디카페 홈페이지 (랜딩형 템플릿)",
    type: ["landing-template", "small-business"],
    tag: "랜딩형 템플릿 · 스터디카페",
    purpose:
      "실시간 잔여석 보드, 시간권·기간권·고정석 요금표, 좌석·시설 안내까지 담은 24시간 스터디카페 원페이지 템플릿입니다.",
    features: ["스크롤 애니메이션", "잔여석 보드", "요금표 탭", "시설 안내"],
    idealFor: "요금과 좌석을 투명하게 열어 신규 방문을 늘리고 싶은 스터디카페 · 독서실",
    image: "/thumbs/study.jpg",
    liveUrl: "/templates/study-landing/",
    industryKey: "study",
  },
  {
    slug: "care-basic-template",
    industry: "요양원·주간보호 홈페이지",
    title: "요양원·주간보호 홈페이지 (기본형 템플릿)",
    type: ["basic-template", "business"],
    tag: "기본형 템플릿 · 요양원",
    purpose:
      "등급별 본인부담금 안내, 하루 일과 타임라인, 입소 절차까지 — 보호자 세대를 위해 큰 글자와 높은 대비로 설계한 요양시설 템플릿입니다.",
    features: ["등급별 비용 안내", "하루 일과 타임라인", "입소 절차", "초대형 전화 상담 CTA"],
    idealFor: "비용을 투명하게 안내해 보호자의 신뢰를 얻고 싶은 요양원 · 주간보호센터",
    image: "/thumbs/care.jpg",
    liveUrl: "/templates/care-basic/",
    industryKey: "care",
  },
  {
    slug: "care-landing-template",
    industry: "요양원·주간보호 홈페이지",
    title: "요양원·주간보호 홈페이지 (랜딩형 템플릿)",
    type: ["landing-template", "business"],
    tag: "랜딩형 템플릿 · 요양원",
    purpose:
      "등급별 본인부담금 안내, 하루 일과 타임라인, 입소 절차까지 — 보호자 세대를 위해 큰 글자와 높은 대비로 설계한 요양시설 원페이지 템플릿입니다.",
    features: ["스크롤 애니메이션", "등급별 비용 안내", "하루 일과", "전화 상담 CTA"],
    idealFor: "비용을 투명하게 안내해 보호자의 신뢰를 얻고 싶은 요양원 · 주간보호센터",
    image: "/thumbs/care.jpg",
    liveUrl: "/templates/care-landing/",
    industryKey: "care",
  },
  {
    slug: "kids-basic-template",
    industry: "어린이집·유치원 홈페이지",
    title: "어린이집·유치원 홈페이지 (기본형 템플릿)",
    type: ["basic-template", "small-business"],
    tag: "기본형 템플릿 · 어린이집",
    purpose:
      "반별 정원표, 하루 일과, 급식 안내, 입소 대기 상담까지 — 크레용 컬러의 도형 콜라주로 담은 어린이집 템플릿입니다.",
    features: ["반별 정원표", "하루 일과", "급식 안내", "입소 대기 상담"],
    idealFor: "학부모에게 하루하루를 투명하게 보여주고 싶은 어린이집 · 유치원",
    image: "/thumbs/kids.jpg",
    liveUrl: "/templates/kids-basic/",
    industryKey: "kids",
  },
  {
    slug: "kids-landing-template",
    industry: "어린이집·유치원 홈페이지",
    title: "어린이집·유치원 홈페이지 (랜딩형 템플릿)",
    type: ["landing-template", "small-business"],
    tag: "랜딩형 템플릿 · 어린이집",
    purpose:
      "반별 정원표, 하루 일과, 급식 안내, 입소 대기 상담까지 — 크레용 컬러의 도형 콜라주로 담은 어린이집 원페이지 템플릿입니다.",
    features: ["스크롤 애니메이션", "도형 콜라주 히어로", "반별 정원표", "입소 상담 문자"],
    idealFor: "학부모에게 하루하루를 투명하게 보여주고 싶은 어린이집 · 유치원",
    image: "/thumbs/kids.jpg",
    liveUrl: "/templates/kids-landing/",
    industryKey: "kids",
  },
  {
    slug: "golf-basic-template",
    industry: "스크린골프 홈페이지",
    title: "스크린골프 홈페이지 (기본형 템플릿)",
    type: ["basic-template", "small-business"],
    tag: "기본형 템플릿 · 스크린골프",
    purpose:
      "시간대별 타석 요금표, 룸·타석 안내, 레슨과 회원권까지 — 샷 트레이서 연출의 다크 톤 스크린골프 템플릿입니다.",
    features: ["시간대별 타석 요금표", "룸 · 타석 안내", "레슨 · 회원권", "예약 문자"],
    idealFor: "예약 문의를 늘리고 싶은 스크린골프장 · 골프연습장",
    image: "/thumbs/golf.jpg",
    liveUrl: "/templates/golf-basic/",
    industryKey: "golf",
  },
  {
    slug: "golf-landing-template",
    industry: "스크린골프 홈페이지",
    title: "스크린골프 홈페이지 (랜딩형 템플릿)",
    type: ["landing-template", "small-business"],
    tag: "랜딩형 템플릿 · 스크린골프",
    purpose:
      "시간대별 타석 요금표, 룸·타석 안내, 레슨과 회원권까지 — 샷 트레이서 연출의 다크 톤 스크린골프 원페이지 템플릿입니다.",
    features: ["샷 트레이서 라인 연출", "타석 요금표", "레슨 안내", "예약 CTA"],
    idealFor: "예약 문의를 늘리고 싶은 스크린골프장 · 골프연습장",
    image: "/thumbs/golf.jpg",
    liveUrl: "/templates/golf-landing/",
    industryKey: "golf",
  },
  {
    slug: "craft-basic-template",
    industry: "공방·클래스 홈페이지",
    title: "공방·클래스 홈페이지 (기본형 템플릿)",
    type: ["basic-template", "small-business"],
    tag: "기본형 템플릿 · 공방·클래스",
    purpose:
      "원데이·정규 클래스 가격, 주간 일정표, 수강생 작품 갤러리까지 — 테라코타 점토 톤의 콜라주형 공방 템플릿입니다.",
    features: ["원데이 클래스 가격", "주간 일정표", "작품 갤러리", "수강 신청 문자"],
    idealFor: "원데이 클래스 예약을 늘리고 싶은 공방 · 스튜디오",
    image: "/thumbs/craft.jpg",
    liveUrl: "/templates/craft-basic/",
    industryKey: "craft",
  },
  {
    slug: "craft-landing-template",
    industry: "공방·클래스 홈페이지",
    title: "공방·클래스 홈페이지 (랜딩형 템플릿)",
    type: ["landing-template", "small-business"],
    tag: "랜딩형 템플릿 · 공방·클래스",
    purpose:
      "원데이·정규 클래스 가격, 주간 일정표, 수강생 작품 갤러리까지 — 테라코타 점토 톤의 콜라주형 공방 원페이지 템플릿입니다.",
    features: ["스크롤 애니메이션", "콜라주 히어로", "주간 일정표", "수강 신청 CTA"],
    idealFor: "원데이 클래스 예약을 늘리고 싶은 공방 · 스튜디오",
    image: "/thumbs/craft.jpg",
    liveUrl: "/templates/craft-landing/",
    industryKey: "craft",
  },
  {
    slug: "tax-basic-template",
    industry: "세무사·회계사무소 홈페이지",
    title: "세무사·회계사무소 홈페이지 (기본형 템플릿)",
    type: ["basic-template", "business"],
    tag: "기본형 템플릿 · 세무·회계",
    purpose:
      "매출 구간별 기장료 요금표, 월별 세무 일정 캘린더, 업무 안내, 세무사 소개까지 — 원장 괘선처럼 정갈하게 담은 사무소 홈페이지 템플릿입니다.",
    features: ["기장료 요금표", "월별 세무 일정", "업무 안내", "상담 문의 문자"],
    idealFor: "기장 거래처를 늘리고 싶은 세무사·회계사무소",
    image: "/thumbs/tax.jpg",
    liveUrl: "/templates/tax-basic/",
    industryKey: "tax",
  },
  {
    slug: "tax-landing-template",
    industry: "세무사·회계사무소 홈페이지",
    title: "세무사·회계사무소 홈페이지 (랜딩형 템플릿)",
    type: ["landing-template", "business"],
    tag: "랜딩형 템플릿 · 세무·회계",
    purpose:
      "괘선 드로잉과 차분한 세리프 연출로, 업무 소개에서 상담 문의까지 신뢰감 있게 이어지는 사무소 원페이지 템플릿입니다.",
    features: ["스크롤 애니메이션", "기장료 요금표", "세무 일정 캘린더", "상담 CTA"],
    idealFor: "전문성과 신뢰로 수임을 늘리고 싶은 세무사·회계사무소",
    image: "/thumbs/tax.jpg",
    liveUrl: "/templates/tax-landing/",
    industryKey: "tax",
  },
  {
    slug: "auto-basic-template",
    industry: "자동차정비소 홈페이지",
    title: "자동차정비소 홈페이지 (기본형 템플릿)",
    type: ["basic-template", "small-business"],
    tag: "기본형 템플릿 · 자동차정비",
    purpose:
      "부품비·공임 분리 공임표, 엔진오일 패키지, 견적 승인 후 작업 원칙까지 — 투명한 정비소의 신뢰를 담은 홈페이지 템플릿입니다.",
    features: ["부품·공임 분리 공임표", "오일 패키지 가격", "작업 과정 안내", "정비 예약 문자"],
    idealFor: "과잉정비 걱정을 덜어주는 투명함으로 단골을 만들고 싶은 정비소·카센터",
    image: "/thumbs/auto.jpg",
    liveUrl: "/templates/auto-basic/",
    industryKey: "auto",
  },
  {
    slug: "auto-landing-template",
    industry: "자동차정비소 홈페이지",
    title: "자동차정비소 홈페이지 (랜딩형 템플릿)",
    type: ["landing-template", "small-business"],
    tag: "랜딩형 템플릿 · 자동차정비",
    purpose:
      "세이프티 오렌지 스플릿 히어로와 인더스트리얼 연출로, 공임표에서 정비 예약까지 이어지는 정비소 원페이지 템플릿입니다.",
    features: ["스크롤 애니메이션", "공임표", "오일 패키지", "예약 문자"],
    idealFor: "강한 첫인상과 예약 전환을 함께 원하는 정비소·수입차 전문점",
    image: "/thumbs/auto.jpg",
    liveUrl: "/templates/auto-landing/",
    industryKey: "auto",
  },
  {
    slug: "flower-basic-template",
    industry: "꽃집·플라워샵 홈페이지",
    title: "꽃집·플라워샵 홈페이지 (기본형 템플릿)",
    type: ["basic-template", "small-business"],
    tag: "기본형 템플릿 · 꽃집",
    purpose:
      "용도별 상품 가격, 당일배달 마감 실시간 배지, 정기구독, 꽃 관리법까지 — 아치형 상품 그리드로 담은 플라워샵 홈페이지 템플릿입니다.",
    features: ["용도별 상품 · 가격", "당일배달 실시간 표시", "정기구독 요금", "주문 문의 문자"],
    idealFor: "전화·문자 주문을 늘리고 싶은 꽃집·플라워스튜디오",
    image: "/thumbs/flower.jpg",
    liveUrl: "/templates/flower-basic/",
    industryKey: "flower",
  },
  {
    slug: "flower-landing-template",
    industry: "꽃집·플라워샵 홈페이지",
    title: "꽃집·플라워샵 홈페이지 (랜딩형 템플릿)",
    type: ["landing-template", "small-business"],
    tag: "랜딩형 템플릿 · 꽃집",
    purpose:
      "보태니컬 세리프와 부드러운 연출로, 상품 감상에서 주문 문의까지 자연스럽게 이어지는 플라워샵 원페이지 템플릿입니다.",
    features: ["스크롤 애니메이션", "용도별 상품 그리드", "정기구독", "주문 문자"],
    idealFor: "감성과 주문 전환을 함께 원하는 꽃집·플라워샵",
    image: "/thumbs/flower.jpg",
    liveUrl: "/templates/flower-landing/",
    industryKey: "flower",
  },
  {
    slug: "dental-basic-template",
    industry: "치과 홈페이지",
    title: "치과 홈페이지 (기본형 템플릿)",
    type: ["basic-template", "small-business"],
    tag: "기본형 템플릿 · 치과",
    purpose:
      "진료 안내, 임플란트 진행 단계 타임라인, 의료법 형식의 비급여 진료비 표, 의료진 소개, 진료 예약 문자까지 담은 치과 홈페이지 템플릿입니다.",
    features: ["실시간 진료중 표시", "임플란트 단계 안내", "비급여 진료비 표", "진료 예약 문자"],
    idealFor: "과잉진료 걱정을 덜어주는 투명한 안내로 신뢰를 쌓고 싶은 치과의원",
    image: "/thumbs/dental.jpg",
    liveUrl: "/templates/dental-basic/",
    industryKey: "dental",
  },
  {
    slug: "dental-landing-template",
    industry: "치과 홈페이지",
    title: "치과 홈페이지 (랜딩형 템플릿)",
    type: ["landing-template", "small-business"],
    tag: "랜딩형 템플릿 · 치과",
    purpose:
      "타임라인 드로잉과 지표 카운터 연출이 더해진 구성으로, 진료 철학에서 예약까지 이어지는 치과 원페이지 템플릿입니다.",
    features: ["스크롤 애니메이션", "임플란트 단계 타임라인", "비급여 진료비 표", "예약 CTA"],
    idealFor: "신뢰감 있는 첫인상과 예약 전환을 함께 원하는 치과의원",
    image: "/thumbs/dental.jpg",
    liveUrl: "/templates/dental-landing/",
    industryKey: "dental",
  },
  {
    slug: "vet-basic-template",
    industry: "동물병원 홈페이지",
    title: "동물병원 홈페이지 (기본형 템플릿)",
    type: ["basic-template", "small-business"],
    tag: "기본형 템플릿 · 동물병원",
    purpose:
      "진료 · 미용 · 호텔 요금 안내, 강아지 · 고양이 예방접종 스케줄, 첫 방문 안내, 예약 문자까지 담은 동물병원 홈페이지 템플릿입니다.",
    features: ["진료 · 미용 · 호텔 요금표", "접종 스케줄 (강아지/고양이)", "야간 응급 안내", "예약 문자"],
    idealFor: "보호자에게 비용과 일정을 투명하게 안내하고 싶은 동물병원 · 애견샵",
    image: "/thumbs/vet.jpg",
    liveUrl: "/templates/vet-basic/",
    industryKey: "vet",
  },
  {
    slug: "vet-landing-template",
    industry: "동물병원 홈페이지",
    title: "동물병원 홈페이지 (랜딩형 템플릿)",
    type: ["landing-template", "small-business"],
    tag: "랜딩형 템플릿 · 동물병원",
    purpose:
      "따뜻한 라운드 연출과 통통 튀는 카드 모션으로, 진료 소개에서 예약 문의까지 부드럽게 이어지는 동물병원 원페이지 템플릿입니다.",
    features: ["스크롤 애니메이션", "요금표 탭", "접종 스케줄 타임라인", "예약 문자"],
    idealFor: "친근한 브랜드 인상과 신규 보호자 유입을 함께 원하는 동물병원",
    image: "/thumbs/vet.jpg",
    liveUrl: "/templates/vet-landing/",
    industryKey: "vet",
  },
  {
    slug: "photo-basic-template",
    industry: "사진관 · 스튜디오 홈페이지",
    title: "사진관 · 스튜디오 홈페이지 (기본형 템플릿)",
    type: ["basic-template", "small-business"],
    tag: "기본형 템플릿 · 사진관",
    purpose:
      "갤러리, 촬영 상품별 가격 · 포함 내역, 촬영 과정 안내, 사진가 소개, FAQ, 촬영 예약 문자로 구성된 다크 갤러리 톤의 사진관 홈페이지 템플릿입니다.",
    features: ["작품 갤러리", "촬영 상품 가격표", "촬영 과정 안내", "촬영 예약 문자"],
    idealFor: "작품과 가격을 함께 보여주고 예약 문의를 받고 싶은 사진관 · 프로필 스튜디오",
    image: "/thumbs/photo.jpg",
    liveUrl: "/templates/photo-basic/",
    industryKey: "photo",
  },
  {
    slug: "photo-landing-template",
    industry: "사진관 · 스튜디오 홈페이지",
    title: "사진관 · 스튜디오 홈페이지 (랜딩형 템플릿)",
    type: ["landing-template", "small-business"],
    tag: "랜딩형 템플릿 · 사진관",
    purpose:
      "인화지가 현상되듯 떠오르는 이미지 연출과 흑백 → 컬러 호버로, 작품 감상에서 촬영 예약까지 이어지는 사진관 원페이지 템플릿입니다.",
    features: ["스크롤 애니메이션", "현상 효과 갤러리", "촬영 상품 가격표", "예약 CTA"],
    idealFor: "작품 감도로 차별화하고 싶은 사진관 · 인물 전문 스튜디오",
    image: "/thumbs/photo.jpg",
    liveUrl: "/templates/photo-landing/",
    industryKey: "photo",
  },
  {
    slug: "beauty-basic-template",
    industry: "미용실 · 뷰티샵 홈페이지",
    title: "미용실 · 뷰티샵 홈페이지 (기본형 템플릿)",
    type: ["basic-template", "small-business"],
    tag: "기본형 템플릿 · 뷰티샵",
    purpose:
      "시술 카테고리별 가격 메뉴판, 스타일 갤러리, 디자이너 소개와 지명 예약 문자까지 — 패션 매거진처럼 정돈한 미용실 홈페이지 템플릿입니다.",
    features: ["시술 가격 메뉴판", "스타일 갤러리", "디자이너 지명 예약", "이용 안내 · 노쇼 규정"],
    idealFor: "가격과 디자이너를 투명하게 보여주고 예약 문의로 연결하고 싶은 미용실 · 네일 · 피부관리샵",
    image: "/thumbs/beauty.jpg",
    liveUrl: "/templates/beauty-basic/",
    industryKey: "beauty",
  },
  {
    slug: "beauty-landing-template",
    industry: "미용실 · 뷰티샵 홈페이지",
    title: "미용실 · 뷰티샵 홈페이지 (랜딩형 템플릿)",
    type: ["landing-template", "small-business"],
    tag: "랜딩형 템플릿 · 뷰티샵",
    purpose:
      "에디토리얼 세리프와 커튼 리빌 연출이 더해진 구성으로, 스타일 감상에서 디자이너 지명 예약까지 이어지는 뷰티샵 원페이지 템플릿입니다.",
    features: ["스크롤 애니메이션", "시술 가격 메뉴판", "디자이너 지명 예약", "예약 문의 문자"],
    idealFor: "브랜드 감도와 예약 전환을 함께 원하는 미용실 · 헤어 살롱",
    image: "/thumbs/beauty.jpg",
    liveUrl: "/templates/beauty-landing/",
    industryKey: "beauty",
  },
  {
    slug: "fitness-basic-template",
    industry: "필라테스 · 헬스장 홈페이지",
    title: "필라테스 · 헬스장 홈페이지 (기본형 템플릿)",
    type: ["basic-template", "small-business"],
    tag: "기본형 템플릿 · 필라테스 · 헬스",
    purpose:
      "요일별 주간 시간표, 회원권 가격표, 코치 자격 소개, 체험 신청 문자로 구성된 피트니스 스튜디오 홈페이지 템플릿입니다.",
    features: ["주간 시간표 (요일 탭)", "회원권 · PT 가격표", "코치 자격 소개", "체험 신청 문자"],
    idealFor: "시간표와 가격을 투명하게 공개하고 체험 신청을 받고 싶은 필라테스 · 헬스 · PT 스튜디오",
    image: "/thumbs/fitness.jpg",
    liveUrl: "/templates/fitness-basic/",
    industryKey: "fitness",
  },
  {
    slug: "fitness-landing-template",
    industry: "필라테스 · 헬스장 홈페이지",
    title: "필라테스 · 헬스장 홈페이지 (랜딩형 템플릿)",
    type: ["landing-template", "small-business"],
    tag: "랜딩형 템플릿 · 필라테스 · 헬스",
    purpose:
      "지표 카운터와 스크롤 연출이 더해진 구성으로, 프로그램 소개에서 체험 신청까지 이어지는 피트니스 원페이지 템플릿입니다.",
    features: ["스크롤 애니메이션", "주간 시간표", "회원권 가격표", "체험 신청 CTA"],
    idealFor: "전문성 있는 첫인상과 체험 전환율을 함께 원하는 필라테스 · 헬스 스튜디오",
    image: "/thumbs/fitness.jpg",
    liveUrl: "/templates/fitness-landing/",
    industryKey: "fitness",
  },
  {
    slug: "stay-basic-template",
    industry: "펜션 · 스테이 홈페이지",
    title: "펜션 · 스테이 홈페이지 (기본형 템플릿)",
    type: ["basic-template", "small-business"],
    tag: "기본형 템플릿 · 펜션 · 스테이",
    purpose:
      "독채 객실별 요금, 성수기 요금 안내, 취소 규정, 이용 안내 아코디언, 날짜·인원 예약 문자까지 담은 감성 스테이 홈페이지 템플릿입니다.",
    features: ["객실별 요금 안내", "성수기 · 취소 규정", "이용 안내 아코디언", "날짜 · 인원 예약 문자"],
    idealFor: "객실과 요금을 정직하게 보여주고 직접 예약 문의를 받고 싶은 펜션 · 독채 스테이",
    image: "/thumbs/stay.jpg",
    liveUrl: "/templates/stay-basic/",
    industryKey: "stay",
  },
  {
    slug: "stay-landing-template",
    industry: "펜션 · 스테이 홈페이지",
    title: "펜션 · 스테이 홈페이지 (랜딩형 템플릿)",
    type: ["landing-template", "small-business"],
    tag: "랜딩형 템플릿 · 펜션 · 스테이",
    purpose:
      "풀스크린 히어로와 느린 줌, 명조 산문 톤의 연출로 머무는 상상을 먼저 하게 만드는 감성 스테이 원페이지 템플릿입니다.",
    features: ["스크롤 애니메이션", "풀스크린 히어로", "객실별 요금 안내", "예약 문의 문자"],
    idealFor: "감성 숙소의 분위기를 그대로 전하고 직접 예약을 늘리고 싶은 펜션 · 스테이",
    image: "/thumbs/stay.jpg",
    liveUrl: "/templates/stay-landing/",
    industryKey: "stay",
  },
  {
    slug: "restaurant-basic-template",
    industry: "음식점 · 카페 홈페이지",
    title: "음식점 · 카페 홈페이지 (기본형 템플릿)",
    type: ["basic-template", "business"],
    tag: "기본형 템플릿 · 음식점 · 카페",
    purpose:
      "실시간 영업중 배지, 카테고리 메뉴판(점선 가격표), 오늘의 추천, 공간 소개, 예약 문의까지 — 메뉴판처럼 정갈하게 구성한 다이닝 템플릿입니다.",
    features: ["실시간 영업중 표시", "카테고리 메뉴판", "오늘의 추천", "전화 · 문자 예약"],
    idealFor: "메뉴와 분위기로 손님을 끌어오고 싶은 식당 · 카페 · 다이닝 바",
    image: "/thumbs/restaurant.jpg",
    liveUrl: "/templates/restaurant-basic/",
    industryKey: "restaurant",
  },
  {
    slug: "restaurant-landing-template",
    industry: "음식점 · 카페 홈페이지",
    title: "음식점 · 카페 홈페이지 (랜딩형 템플릿)",
    type: ["landing-template", "business"],
    tag: "랜딩형 템플릿 · 음식점 · 카페",
    purpose:
      "세리프 타이포와 스크롤 연출이 더해진 프리미엄 구성으로, 메뉴 감상에서 예약까지 자연스럽게 이어지는 다이닝 원페이지 템플릿입니다.",
    features: ["스크롤 애니메이션", "실시간 영업중 표시", "카테고리 메뉴판", "인원 선택 예약 문자"],
    idealFor: "브랜드 감도와 예약 전환을 함께 원하는 식당 · 카페 · 다이닝 바",
    image: "/thumbs/restaurant.jpg",
    liveUrl: "/templates/restaurant-landing/",
    industryKey: "restaurant",
  },
  {
    slug: "corporate-basic-template",
    industry: "기업 · 브랜드 홈페이지",
    title: "기업 · 브랜드 홈페이지 (기본형 템플릿)",
    type: ["basic-template", "business"],
    tag: "기본형 템플릿 · 기업 · 브랜드",
    purpose:
      "사업영역 · 핵심 지표 · 연혁 · 함께한 기업 · 뉴스룸 · 견적 문의로 구성된 B2B 기업 홈페이지 템플릿입니다. 과장 없이 숫자로 신뢰를 만듭니다.",
    features: ["사업영역 그리드", "핵심 지표 카운터", "연혁 타임라인", "견적 문의 폼"],
    idealFor: "제조 · 솔루션 · 전문 서비스 등 신뢰가 곧 영업인 B2B 기업",
    image: "/thumbs/corporate.jpg",
    liveUrl: "/templates/corporate-basic/",
    industryKey: "corporate",
  },
  {
    slug: "corporate-landing-template",
    industry: "기업 · 브랜드 홈페이지",
    title: "기업 · 브랜드 홈페이지 (랜딩형 템플릿)",
    type: ["landing-template", "business"],
    tag: "랜딩형 템플릿 · 기업 · 브랜드",
    purpose:
      "그라파이트 히어로와 그리드 연출의 스위스 스타일 구성으로, 회사 소개에서 견적 문의까지 이어지는 기업 원페이지 템플릿입니다.",
    features: ["스크롤 애니메이션", "지표 카운터", "연혁 타임라인", "다크 문의 섹션"],
    idealFor: "정제된 첫인상이 필요한 기업 · 브랜드 · 스타트업",
    image: "/thumbs/corporate.jpg",
    liveUrl: "/templates/corporate-landing/",
    industryKey: "corporate",
  },
  {
    slug: "interior-basic-template",
    industry: "인테리어 · 리모델링 홈페이지",
    title: "인테리어 · 리모델링 홈페이지 (기본형 템플릿)",
    type: ["basic-template", "business"],
    tag: "기본형 템플릿 · 인테리어",
    purpose:
      "프로젝트 갤러리 · 시공 전후 비교 · 주차별 공정 · 평형별 비용표 · 자재 기준 · FAQ까지, 도면처럼 정돈된 인테리어 업체 홈페이지 템플릿입니다.",
    features: ["시공 전후 비교 슬라이더", "평형별 비용 계산", "8주 공정 타임라인", "자재 기준 · A/S 보증"],
    idealFor: "견적 투명성과 포트폴리오로 신뢰를 쌓고 싶은 인테리어 · 리모델링 업체",
    image: "/thumbs/interior.jpg",
    liveUrl: "/templates/interior-basic/",
    industryKey: "interior",
  },
  {
    slug: "interior-landing-template",
    industry: "인테리어 · 리모델링 홈페이지",
    title: "인테리어 · 리모델링 홈페이지 (랜딩형 템플릿)",
    type: ["landing-template", "business"],
    tag: "랜딩형 템플릿 · 인테리어",
    purpose:
      "치수선 · 도면 모티프의 스크롤 연출이 더해진 프리미엄 구성으로, 프로젝트 감상에서 상담 신청까지 자연스럽게 이어지는 템플릿입니다.",
    features: ["스크롤 애니메이션", "시공 전후 비교 슬라이더", "평형별 비용 계산", "상담 신청 폼"],
    idealFor: "감각적인 첫인상과 상담 전환을 함께 원하는 인테리어 · 리모델링 업체",
    image: "/thumbs/interior.jpg",
    liveUrl: "/templates/interior-landing/",
    industryKey: "interior",
  },
  {
    slug: "rentcar-basic-template",
    industry: "렌트카 홈페이지",
    title: "렌트카 홈페이지 (기본형 템플릿)",
    type: ["basic-template", "business"],
    tag: "기본형 템플릿 · 렌트카",
    purpose:
      "차종 필터 라인업 · 대여료 계산기 · 장기렌트 요금표 · 보험 비교 · 이용 규정 · FAQ로 구성된 렌트카 업체 홈페이지 템플릿입니다.",
    features: ["차종 필터 라인업", "대여료 즉시 계산", "장기렌트 · 부가옵션", "보험 비교표"],
    idealFor: "요금을 투명하게 공개하고 전화 예약으로 연결하고 싶은 렌트카 업체",
    image: "/thumbs/rentcar.jpg",
    liveUrl: "/templates/rentcar-basic/",
    industryKey: "rentcar",
  },
  {
    slug: "rentcar-landing-template",
    industry: "렌트카 홈페이지",
    title: "렌트카 홈페이지 (랜딩형 템플릿)",
    type: ["landing-template", "business"],
    tag: "랜딩형 템플릿 · 렌트카",
    purpose:
      "번호판 · 차선 모티프의 스피드감 있는 스크롤 연출로, 차량 탐색에서 요금 계산 · 예약 전화까지 이어지는 원페이지 템플릿입니다.",
    features: ["스크롤 애니메이션", "차종 필터 라인업", "대여료 즉시 계산", "예약 전화 CTA"],
    idealFor: "젊은 감각의 브랜드 인상과 예약 전환을 원하는 렌트카 업체",
    image: "/thumbs/rentcar.jpg",
    liveUrl: "/templates/rentcar-landing/",
    industryKey: "rentcar",
  },
  {
    slug: "moving-basic-template",
    industry: "이사 · 청소업체 홈페이지",
    title: "이사 · 청소업체 홈페이지 (기본형 템플릿)",
    type: ["basic-template", "business"],
    tag: "기본형 템플릿 · 이사 · 청소",
    purpose:
      "간편 견적 계산기 · 작업 전후 비교 · 이사 준비표 · 보상 절차 · 요금 공개 · FAQ까지, 견적서처럼 투명하게 구성한 이사 · 청소업체 템플릿입니다.",
    features: ["30초 간편 견적", "작업 전후 비교 슬라이더", "이사 준비 체크리스트", "파손 보상 절차"],
    idealFor: "추가 요금 없는 투명한 견적을 강점으로 내세우는 이사 · 청소업체",
    image: "/thumbs/moving.jpg",
    liveUrl: "/templates/moving-basic/",
    industryKey: "moving",
  },
  {
    slug: "moving-landing-template",
    industry: "이사 · 청소업체 홈페이지",
    title: "이사 · 청소업체 홈페이지 (랜딩형 템플릿)",
    type: ["landing-template", "business"],
    tag: "랜딩형 템플릿 · 이사 · 청소",
    purpose:
      "견적 전표 · 테이프 · 손글씨 메모 등 현장의 물성을 살린 스크롤 연출로, 견적 계산에서 전화 상담까지 이어지는 원페이지 템플릿입니다.",
    features: ["스크롤 애니메이션", "30초 간편 견적", "작업 전후 비교 슬라이더", "전화 상담 CTA"],
    idealFor: "동네 업체다운 진정성과 견적 전환을 함께 원하는 이사 · 청소업체",
    image: "/thumbs/moving.jpg",
    liveUrl: "/templates/moving-landing/",
    industryKey: "moving",
  },
  {
    slug: "academy-basic-template",
    industry: "학원 홈페이지",
    title: "학원 홈페이지 (기본형 템플릿)",
    type: ["basic-template", "business"],
    tag: "기본형 템플릿 · 학원",
    purpose:
      "과정안내 · 커리큘럼 · 강사진 · 시간표 · 오시는 길 구성을 학년별로 정돈해 담은 학원 홈페이지 템플릿입니다.",
    features: ["학년별 과정 안내", "학습 관리 커리큘럼", "강사진 소개", "시간표 · 오시는 길"],
    idealFor: "수업 구성과 관리 방식을 신뢰감 있게 보여주고 상담 신청으로 연결하고 싶은 학원 · 교습소",
    image: "/thumbs/academy.jpg",
    liveUrl: "/templates/academy-basic/",
    industryKey: "academy",
  },
  {
    slug: "academy-landing-template",
    industry: "학원 홈페이지",
    title: "학원 홈페이지 (랜딩형 템플릿)",
    type: ["landing-template", "business"],
    tag: "랜딩형 템플릿 · 학원",
    purpose:
      "스크롤 연출이 더해진 원페이지 구성으로, 학년별 과정과 학습 관리 방식을 따라 읽다 자연스럽게 상담 신청까지 이어지는 학원 홈페이지 템플릿입니다.",
    features: ["스크롤 애니메이션", "학년별 과정 안내", "강사진 소개", "상담 신청 CTA"],
    idealFor: "학원의 관리 방식을 흐름 있게 보여주고 상담 전환율을 함께 끌어올리고 싶은 학원 · 교습소",
    image: "/thumbs/academy.jpg",
    liveUrl: "/templates/academy-landing/",
    industryKey: "academy",
  },
  {
    slug: "clinic-basic-template",
    industry: "병원 · 의원 홈페이지",
    title: "병원 · 의원 홈페이지 (기본형 템플릿)",
    type: ["basic-template", "business"],
    tag: "기본형 템플릿 · 병원 · 의원",
    purpose:
      "진료안내 · 의료진 · 둘러보기 · 진료시간 · 오시는길 구성을 차분하고 신뢰감 있게 담은 의원 홈페이지 템플릿입니다.",
    features: ["진료과목 안내", "의료진 소개", "시설 둘러보기", "진료시간 · 오시는 길"],
    idealFor: "신뢰감 있는 첫인상과 예약 문의 연결이 필요한 병 · 의원, 클리닉",
    image: "/thumbs/clinic.jpg",
    liveUrl: "/templates/clinic-basic/",
    industryKey: "hospital",
  },
  {
    slug: "clinic-landing-template",
    industry: "병원 · 의원 홈페이지",
    title: "병원 · 의원 홈페이지 (랜딩형 템플릿)",
    type: ["landing-template", "business"],
    tag: "랜딩형 템플릿 · 병원 · 의원",
    purpose:
      "스크롤 연출이 더해진 프리미엄 원페이지 구성으로, 방문자가 자연스럽게 예약 문의까지 이어지는 의원 홈페이지 템플릿입니다.",
    features: ["스크롤 애니메이션", "진료과목 안내", "의료진 소개", "온라인 예약 CTA"],
    idealFor: "브랜드 인상과 예약 전환율을 함께 끌어올리고 싶은 병 · 의원, 클리닉",
    image: "/thumbs/clinic.jpg",
    liveUrl: "/templates/clinic-landing/",
    industryKey: "hospital",
  },
  {
    slug: "real-estate-basic-template",
    industry: "부동산 중개업소 홈페이지",
    title: "부동산 홈페이지 (기본형 템플릿)",
    type: ["basic-template", "small-business"],
    tag: "기본형 템플릿 · 부동산",
    purpose:
      "거래유형 필터 매물 장부, 법정 중개보수 계산기, 거래 절차 안내, FAQ까지 — 매물이 많아 보이게 설계한 부동산 중개업소 홈페이지 템플릿입니다.",
    features: ["매물 장부 · 거래유형 필터", "중개보수 계산기", "거래 절차 안내", "FAQ · 오시는 길"],
    idealFor: "보유 매물을 전부 보여주고 방문 상담으로 연결하고 싶은 공인중개사사무소",
    image: "/thumbs/realestate.jpg",
    liveUrl: "/templates/realestate-basic/",
    industryKey: "real-estate",
  },
  {
    slug: "real-estate-landing-template",
    industry: "부동산 중개업소 홈페이지",
    title: "부동산 홈페이지 (랜딩형 템플릿)",
    type: ["landing-template", "small-business"],
    tag: "랜딩형 템플릿 · 부동산",
    purpose:
      "장부 넘기듯 매물을 훑는 스크롤 연출에 거래유형 필터, 중개보수 계산기, 도장 스탬프 디테일까지 더한 부동산 원페이지 템플릿입니다.",
    features: ["스크롤 애니메이션", "매물 장부 · 필터", "중개보수 계산기", "전화 상담 CTA"],
    idealFor: "매물 물량과 신뢰감을 동시에 보여주고 싶은 공인중개사사무소",
    image: "/thumbs/realestate.jpg",
    liveUrl: "/templates/realestate-landing/",
    industryKey: "real-estate",
  },
  {
    slug: "commercial-real-estate-platform",
    industry: "상업용 부동산 플랫폼",
    title: "상업용 부동산 플랫폼 구축",
    type: ["platform"],
    tag: "플랫폼 · 부동산",
    purpose:
      "지도 기반 매물 검색부터 상담 접수, 매물·고객·일정 관리까지 하나의 시스템으로 연결한 상업용 부동산 플랫폼 구축 사례입니다.",
    features: ["지도 기반 검색", "매물 관리", "관리자 CMS", "문의 CRM", "반응형"],
    idealFor:
      "매물 검색, 상담 접수부터 매물·고객·일정·직원 관리까지 하나의 시스템으로 운영하고 싶은 부동산 중개·분양 플랫폼",
    image: "/thumbs/realestate.jpg",
    detailHref: "/web-solutions/real-estate",
  },
  {
    slug: "hospital-solution",
    industry: "병원 · 의원 고객 + 관리자 시스템",
    title: "병원 · 의원 홈페이지 + 관리자 시스템",
    type: ["platform", "business"],
    tag: "플랫폼 · 병원 · 의원",
    purpose:
      "진료과목 · 의료진 · 공지를 관리자 페이지에서 등록하면 고객용 홈페이지에 실시간 반영되는 병원 · 의원 운영 시스템 구축 사례입니다.",
    features: ["진료과목 안내", "의료진 소개", "공지 · 이벤트 관리", "예약 문의 접수", "관리자 페이지"],
    idealFor: "홈페이지 콘텐츠를 직접 수정 · 운영하고 싶은 병 · 의원, 클리닉",
    image: "/thumbs/clinic.jpg",
    liveUrl: "/templates/clinic-landing/",
    adminDemoHref: "/web-solutions/hospital/demo",
  },
  {
    slug: "academy-solution",
    industry: "학원 고객 + 관리자 시스템",
    title: "학원 홈페이지 + 관리자 시스템",
    type: ["platform", "business"],
    tag: "플랫폼 · 학원",
    purpose:
      "개설 강의와 강사 정보를 관리자 페이지에서 등록 · 관리하고, 고객용 홈페이지에서 과목별로 탐색 · 상담 신청까지 이어지는 학원 운영 시스템 구축 사례입니다.",
    features: ["개설 강의 안내", "과목별 필터", "상담 신청 접수", "강의 · 강사 관리", "관리자 페이지"],
    idealFor: "강의 개설 · 마감을 수시로 업데이트해야 하는 학원 · 교습소",
    image: "/thumbs/academy.jpg",
    liveUrl: "/templates/academy-landing/",
    adminDemoHref: "/web-solutions/academy/demo",
  },
  {
    slug: "rentcar-solution",
    industry: "렌트카 고객 + 관리자 시스템",
    title: "렌트카 홈페이지 + 관리자 시스템",
    type: ["platform", "business"],
    tag: "플랫폼 · 렌트카",
    purpose:
      "차종 · 가격대 · 지점별 차량 검색과 상담 문의 접수, 차량 등록 · 관리까지 하나로 연결한 렌트카 운영 시스템 구축 사례입니다.",
    features: ["차량 검색 · 필터", "차량 등록 관리", "상담 문의 접수", "지점 안내", "관리자 페이지"],
    idealFor: "보유 차량을 직접 등록 · 관리하며 운영하고 싶은 렌터카 · 리스 업체",
    image: "/thumbs/rentcar.jpg",
    liveUrl: "https://roadin.netlify.app/",
    adminDemoHref: "/web-solutions/rentcar/demo",
  },
  {
    slug: "interior-solution",
    industry: "인테리어 고객 + 관리자 시스템",
    title: "인테리어 홈페이지 + 관리자 시스템",
    type: ["platform", "business"],
    tag: "플랫폼 · 인테리어",
    purpose:
      "평형대별 시공 사례를 관리자 페이지에서 등록하면 고객용 홈페이지에 바로 반영되고, 견적 문의 접수까지 이어지는 인테리어 운영 시스템 구축 사례입니다.",
    features: ["시공 사례 관리", "평형대별 필터", "견적 문의 접수", "관리자 페이지"],
    idealFor: "시공 사례를 계속 쌓아가며 영업 자산으로 쓰고 싶은 인테리어 · 리모델링 업체",
    image: "/thumbs/interior.jpg",
    liveUrl: "https://objetbath.netlify.app/",
    adminDemoHref: "/web-solutions/interior/demo",
  },
  {
    slug: "moving-solution",
    industry: "이사 · 청소 고객 + 관리자 시스템",
    title: "이사 · 청소 홈페이지 + 관리자 시스템",
    type: ["platform", "small-business"],
    tag: "플랫폼 · 이사 · 청소",
    purpose:
      "서비스 안내와 지역별 작업 사례를 관리자 페이지에서 관리하고, 견적 문의 접수로 이어지는 이사 · 청소 업체 운영 시스템 구축 사례입니다.",
    features: ["서비스 안내", "지역별 작업 사례 관리", "견적 문의 접수", "관리자 페이지"],
    idealFor: "작업 사례와 견적 문의를 체계적으로 관리하고 싶은 이사 · 청소 업체",
    image: "/thumbs/moving.jpg",
    detailHref: "/web-solutions/moving",
  },
  {
    slug: "roadin-rentcar",
    industry: "렌터카 홈페이지",
    title: "멀티브랜드 렌터카 홈페이지",
    type: ["business"],
    tag: "기업 · 렌터카",
    purpose: "국산부터 수입차까지 조건별로 차량을 비교하고 견적을 받을 수 있는 멀티브랜드 렌터카 비교 플랫폼 홈페이지 포트폴리오입니다.",
    features: ["조건별 차량 필터링", "차급별 요금 비교표", "전국 지점 안내", "실시간 견적 신청"],
    idealFor: "다양한 차량 재고를 한눈에 비교해서 보여주고 싶은 렌터카·리스 업체",
    image: roadinImg,
    liveUrl: "https://roadin.netlify.app/",
  },
  {
    slug: "carplan-rentcar",
    industry: "장기렌트카 홈페이지",
    title: "장기렌트카 상담 홈페이지",
    type: ["business"],
    tag: "기업 · 장기렌트",
    purpose: "실시간 계약 현황과 고객 후기로 신뢰감을 전달하고 장기렌트·리스 상담으로 자연스럽게 연결하는 렌터카 홈페이지 포트폴리오입니다.",
    features: ["실시간 계약 카운터", "차종별 월 렌트료 비교", "고객 후기 슬라이더", "무심사 상담 프로그램 안내"],
    idealFor: "신뢰 지표와 실시간성으로 상담 전환을 높이고 싶은 장기렌트·리스 업체",
    image: carplanImg,
    liveUrl: "https://carplanrentcar.netlify.app/",
  },
  {
    slug: "objetbath",
    industry: "욕실 리모델링 홈페이지",
    title: "욕실 리모델링 홈페이지",
    type: ["business", "portfolio"],
    tag: "기업 · 리모델링",
    purpose: "아파트 욕실 리모델링 상담부터 시공, 마감 점검까지 전문적으로 안내하는 욕실 리모델링 브랜드 홈페이지 포트폴리오입니다.",
    features: ["시공 사례 Before/After", "패키지별 견적 비교", "온라인 예산 계산기", "카카오톡 사진 상담"],
    idealFor: "시공 전후 비교와 신뢰감 있는 상담 과정을 보여주고 싶은 인테리어·리모델링 업체",
    image: objetbathImg,
    liveUrl: "https://objetbath.netlify.app/",
  },
  {
    slug: "nexmotion",
    industry: "제조/자동화 기업 홈페이지",
    title: "제조/자동화 기업 홈페이지",
    type: ["business"],
    tag: "기업 · 산업 자동화",
    purpose: "로봇 자동화, AI Vision, 스마트팩토리 솔루션을 기술 중심으로 신뢰감 있게 전달하는 제조/자동화 기업 홈페이지 포트폴리오입니다.",
    features: ["솔루션/장비 라인업 소개", "산업별 적용 사례", "공정 단계 스토리텔링", "프로젝트 문의 폼"],
    idealFor: "기술력과 전문성을 강조하고 싶은 제조·엔지니어링·B2B 기업",
    image: nexmotionImg,
    liveUrl: "https://nexmotion.netlify.app/",
  },
  {
    slug: "moving-company",
    industry: "이삿짐센터 홈페이지",
    title: "이삿짐센터 홈페이지",
    type: ["one-page", "small-business"],
    tag: "원페이지 · 소상공인",
    purpose: "서비스 종류와 신뢰 요소를 한눈에 보여주고 무료 견적 신청으로 자연스럽게 연결되는 이삿짐센터 홈페이지 포트폴리오입니다.",
    features: ["서비스 종류 안내", "무료 견적 신청 폼", "고객 후기 슬라이더", "전화/카카오 상담 연결"],
    idealFor: "견적 문의 전환이 중요한 이사·용달 서비스 업체",
    image: movingImg,
    liveUrl: "https://24com.netlify.app/design-1",
  },
  {
    slug: "mujin-shop",
    industry: "쇼핑몰 홈페이지",
    title: "쇼핑몰 홈페이지",
    type: ["business", "shopping-mall"],
    tag: "기업 · 쇼핑몰",
    purpose: "데일리 의류 브랜드의 제품 라인업과 사이즈 가이드를 감각적으로 담은 커머스형 쇼핑몰 홈페이지 포트폴리오입니다.",
    features: ["상품 상세/사이즈 가이드", "리뷰·후기 섹션", "회원 등급 혜택 안내", "뉴스레터 구독"],
    idealFor: "온라인으로 제품을 직접 판매하고 싶은 패션·리테일 브랜드",
    image: mujinImg,
    liveUrl: "https://mujinshop.netlify.app/",
  },
  {
    slug: "aura-academy",
    industry: "입시학원 홈페이지",
    title: "입시학원 홈페이지",
    type: ["business"],
    tag: "기업 · 교육",
    purpose: "1:1 학습 진단과 맞춤 커리큘럼을 신뢰감 있게 전달하는 프리미엄 입시학원 홈페이지 포트폴리오입니다.",
    features: ["학습 진단 프로그램 소개", "커리큘럼 안내", "상담 신청 폼", "레벨테스트 연결"],
    idealFor: "전문성과 신뢰감을 강조하고 싶은 입시·교육 브랜드",
    image: auraImg,
    liveUrl: "https://aura-academy.netlify.app/",
  },
  {
    slug: "olea-food-brand",
    industry: "식품 브랜드 홈페이지",
    title: "식품 브랜드 홈페이지",
    type: ["business"],
    tag: "기업 · 식품 브랜드",
    purpose: "프리미엄 올리브오일 브랜드의 제품 라인업과 브랜드 스토리를 감각적으로 담은 식품 브랜드 홈페이지 포트폴리오입니다.",
    features: ["제품 라인업 소개", "브랜드 스토리텔링", "쇼핑몰형 구매 연결", "뉴스레터 구독"],
    idealFor: "제품과 브랜드 감성을 함께 보여주고 싶은 식품·리테일 브랜드",
    image: oleaImg,
    liveUrl: "https://oleaoil.netlify.app/",
  },
  {
    slug: "hospital",
    industry: "병원 홈페이지",
    title: "병원 홈페이지",
    type: ["business"],
    tag: "기업",
    purpose: "진료 정보, 의료진 소개, 위치 안내를 신뢰감 있게 정리한 병원 / 의원형 홈페이지 포트폴리오입니다.",
    features: ["진료과목 안내", "의료진 소개", "오시는 길/지도", "예약·전화 문의 버튼"],
    idealFor: "신뢰감 있는 정보 전달이 우선인 병·의원, 한의원",
    image: hospitalImg,
  },
  {
    slug: "beauty",
    industry: "뷰티샵 홈페이지",
    title: "뷰티샵 홈페이지",
    type: ["small-business"],
    tag: "소상공인",
    purpose: "시술 이미지와 매장 분위기를 중심으로 구성해 예약 문의로 이어지도록 설계한 뷰티 업종 홈페이지 포트폴리오입니다.",
    features: ["시술 메뉴/가격표", "시술 사진 갤러리", "카카오톡 상담 연결", "오시는 길"],
    idealFor: "네일샵, 헤어샵, 피부관리실 등 예약 기반 매장",
    image: beautySkincareImg,
  },
  {
    slug: "korean-restaurant",
    industry: "한식당 홈페이지",
    title: "한식당 홈페이지",
    type: ["small-business", "one-page"],
    tag: "소상공인 · 원페이지",
    purpose: "메뉴와 매장 분위기를 중심으로 구성하고 전화 / 지도 / 예약으로 자연스럽게 연결되는 외식업 홈페이지 포트폴리오입니다.",
    features: ["대표 메뉴 소개", "메뉴판/가격 안내", "매장 사진", "지도/전화 연결"],
    idealFor: "단골 확보와 신규 방문객 유입이 모두 필요한 식당",
    image: koreanRestaurantImg,
  },
  {
    slug: "interior-construction",
    industry: "인테리어 / 건설 홈페이지",
    title: "인테리어 / 건설 홈페이지",
    type: ["business", "portfolio", "renewal"],
    tag: "기업 · 포트폴리오",
    purpose: "시공 사례와 전문성을 중심으로 보여주는 건설 / 인테리어 업종 홈페이지 포트폴리오입니다.",
    features: ["시공 사례 갤러리", "작업 절차 안내", "견적 문의 폼", "회사 소개"],
    idealFor: "시공 사례를 자산으로 활용하고 싶은 인테리어·건설업체",
    image: interiorConstructionImg,
  },
  {
    slug: "move-in-cleaning",
    industry: "입주청소 홈페이지",
    title: "입주청소 홈페이지",
    type: ["one-page", "small-business"],
    tag: "원페이지 · 소상공인",
    purpose: "서비스 범위, 작업 전후 이미지, 문의 연결을 한 페이지 흐름으로 정리한 청소 서비스 홈페이지 포트폴리오입니다.",
    features: ["서비스 범위 안내", "청소 전후 사진", "빠른 전화/카카오톡 문의", "간단 견적 안내"],
    idealFor: "문의 전화 응대 부담을 줄이고 싶은 청소 업체",
    image: moveInCleaningImg,
  },
  {
    slug: "corporate",
    industry: "기업 소개 홈페이지",
    title: "기업 소개 홈페이지",
    type: ["business", "renewal"],
    tag: "기업 · 리뉴얼",
    purpose: "사업 영역, 연혁, 연락처를 정리해 회사에 대한 신뢰를 주는 정보 전달형 구성입니다.",
    features: ["사업 영역 소개", "회사 연혁/개요", "오시는 길", "문의 폼"],
    idealFor: "홈페이지가 없거나 정보가 오래된 중소기업, 스타트업",
    image: corporateImg,
  },
];

/**
 * 포트폴리오(=실제 제작 사례) 목록. 판매용 템플릿(industryKey 항목)은 랜딩형만 대표로
 * 포함한다(기본형은 디자인이 같아 카드가 중복돼 보이므로 /templates에서만 노출).
 * 새 템플릿을 SAMPLES에 추가하면 포트폴리오·메인 슬라이더에 자동 반영된다.
 */
export const PORTFOLIO_SAMPLES: Sample[] = SAMPLES.filter(
  (s) => !s.industryKey || s.type?.includes("landing-template"),
);

/**
 * 메인페이지 PORTFOLIO 섹션에 고정 노출하는 업종별 대표 사례 6건.
 * 새 포트폴리오를 배열 앞에 추가해도 메인 화면 구성이 밀리지 않도록 슬러그로 고정한다.
 * (필터를 선택했을 때는 아래 고정 목록 대신 해당 분류 전체에서 보여준다.)
 */
const MAIN_PORTFOLIO_SLUGS = [
  "commercial-real-estate-platform",
  "hospital-solution",
  "academy-solution",
  "rentcar-solution",
  "interior-solution",
  "moving-solution",
];

export const MAIN_PORTFOLIO_SAMPLES: Sample[] = MAIN_PORTFOLIO_SLUGS.map(
  (slug) => PORTFOLIO_SAMPLES.find((s) => s.slug === slug),
).filter((s): s is Sample => Boolean(s));

/**
 * 메인 슬라이더: 고정 6건 뒤에 나머지 포트폴리오 전체를 자동으로 이어 붙인다.
 * SAMPLES에 항목을 추가/수정하면 별도 작업 없이 메인 슬라이더에도 반영된다.
 * roadin · objetbath는 위 솔루션 카드와 같은 사이트라 중복 노출을 피하려고 제외한다.
 */
const CAROUSEL_EXCLUDED_SLUGS = ["roadin-rentcar", "objetbath"];

export const MAIN_PORTFOLIO_CAROUSEL: Sample[] = [
  ...MAIN_PORTFOLIO_SAMPLES,
  ...PORTFOLIO_SAMPLES.filter(
    (s) => !MAIN_PORTFOLIO_SLUGS.includes(s.slug) && !CAROUSEL_EXCLUDED_SLUGS.includes(s.slug),
  ),
];

export const PORTFOLIO_FILTERS = [
  { label: "전체", value: "all" },
  { label: "플랫폼·시스템", value: "platform" },
  { label: "원페이지", value: "one-page" },
  { label: "소상공인", value: "small-business" },
  { label: "기업", value: "business" },
  { label: "쇼핑몰", value: "shopping-mall" },
  { label: "포트폴리오", value: "portfolio" },
  { label: "리뉴얼", value: "renewal" },
];

/**
 * 업종 key → 표시 라벨. 새 업종 템플릿을 추가할 때 여기에 라벨을 넣고 SAMPLES 항목에
 * industryKey를 지정하면, /templates 업종 필터에 자동으로 칩이 하나 늘어난다.
 */
const TEMPLATE_INDUSTRY_LABELS: Record<string, string> = {
  "real-estate": "부동산",
  rentcar: "렌트카",
  hospital: "병원·의원",
  academy: "학원",
  interior: "인테리어·리모델링",
  moving: "이사·청소업체",
  restaurant: "음식점·카페",
  corporate: "기업·브랜드",
  beauty: "뷰티샵",
  fitness: "필라테스·헬스",
  stay: "펜션·스테이",
  dental: "치과",
  vet: "동물병원",
  photo: "사진관",
  tax: "세무·회계",
  auto: "자동차정비",
  flower: "꽃집",
  law: "법률사무소",
  study: "스터디카페",
  care: "요양원·주간보호",
  kids: "어린이집·유치원",
  golf: "스크린골프",
  craft: "공방·클래스",
  usedcar: "중고차",
};

/** 실제로 템플릿이 존재하는 업종만 필터로 노출한다 (준비 안 된 업종 칩을 띄우지 않는다). */
export const TEMPLATE_INDUSTRY_FILTERS = [
  { label: "전체", value: "all" },
  ...Object.entries(TEMPLATE_INDUSTRY_LABELS)
    .filter(([key]) => SAMPLES.some((s) => s.industryKey === key))
    .map(([value, label]) => ({ label, value })),
];

export function getSampleBySlug(slug: string): Sample | undefined {
  return SAMPLES.find((s) => s.slug === slug);
}
